// ═══════════════════════════════════════════════════════════════
// PROJECT DOMAIN TAXONOMY
// 550+ project-specific domains organized by category
// Covers: Software, AI/ML, Hardware, Creative, Research,
//         Community, Open Source, Game Dev, Side Projects, Web3
// ═══════════════════════════════════════════════════════════════

export interface ProjectDomain {
  name: string
  slug: string
  category: string
  aliases?: string[]
  popular?: boolean
}

export const PROJECT_DOMAINS: ProjectDomain[] = [

  // ─── SOFTWARE ENGINEERING (100+) ───
  { name: 'Web Development', slug: 'web-dev', category: 'Software Engineering', popular: true },
  { name: 'Frontend Development', slug: 'frontend', category: 'Software Engineering', popular: true },
  { name: 'Backend Development', slug: 'backend', category: 'Software Engineering', popular: true },
  { name: 'Full-Stack Development', slug: 'fullstack', category: 'Software Engineering', popular: true },
  { name: 'Mobile Development', slug: 'mobile-dev', category: 'Software Engineering', popular: true },
  { name: 'iOS Development', slug: 'ios', category: 'Software Engineering' },
  { name: 'Android Development', slug: 'android', category: 'Software Engineering' },
  { name: 'React Native', slug: 'react-native', category: 'Software Engineering' },
  { name: 'Flutter', slug: 'flutter', category: 'Software Engineering' },
  { name: 'Cross-Platform Apps', slug: 'cross-platform', category: 'Software Engineering' },
  { name: 'Progressive Web Apps', slug: 'pwa', category: 'Software Engineering' },
  { name: 'Desktop Apps', slug: 'desktop-apps', category: 'Software Engineering' },
  { name: 'Electron Apps', slug: 'electron', category: 'Software Engineering' },
  { name: 'Tauri Apps', slug: 'tauri', category: 'Software Engineering' },
  { name: 'Browser Extensions', slug: 'browser-extensions', category: 'Software Engineering' },
  { name: 'Chrome Extensions', slug: 'chrome-extensions', category: 'Software Engineering' },
  { name: 'VS Code Extensions', slug: 'vscode-extensions', category: 'Software Engineering' },
  { name: 'CLI Tools', slug: 'cli-tools', category: 'Software Engineering', popular: true },
  { name: 'Developer Tools', slug: 'devtools', category: 'Software Engineering', popular: true },
  { name: 'DevOps', slug: 'devops', category: 'Software Engineering', popular: true },
  { name: 'CI/CD Pipelines', slug: 'ci-cd', category: 'Software Engineering' },
  { name: 'Docker', slug: 'docker', category: 'Software Engineering' },
  { name: 'Kubernetes', slug: 'kubernetes', category: 'Software Engineering' },
  { name: 'Infrastructure as Code', slug: 'iac', category: 'Software Engineering' },
  { name: 'Terraform', slug: 'terraform', category: 'Software Engineering' },
  { name: 'Cloud Native', slug: 'cloud-native', category: 'Software Engineering' },
  { name: 'AWS Projects', slug: 'aws', category: 'Software Engineering' },
  { name: 'Google Cloud Projects', slug: 'gcp', category: 'Software Engineering' },
  { name: 'Azure Projects', slug: 'azure', category: 'Software Engineering' },
  { name: 'Serverless', slug: 'serverless', category: 'Software Engineering' },
  { name: 'Edge Computing', slug: 'edge-computing', category: 'Software Engineering' },
  { name: 'Microservices', slug: 'microservices', category: 'Software Engineering' },
  { name: 'API Development', slug: 'api-dev', category: 'Software Engineering', popular: true },
  { name: 'REST APIs', slug: 'rest-apis', category: 'Software Engineering' },
  { name: 'GraphQL', slug: 'graphql', category: 'Software Engineering' },
  { name: 'gRPC', slug: 'grpc', category: 'Software Engineering' },
  { name: 'WebSockets', slug: 'websockets', category: 'Software Engineering' },
  { name: 'Real-time Systems', slug: 'realtime', category: 'Software Engineering' },
  { name: 'Databases', slug: 'databases', category: 'Software Engineering' },
  { name: 'PostgreSQL Projects', slug: 'postgres', category: 'Software Engineering' },
  { name: 'MongoDB Projects', slug: 'mongodb', category: 'Software Engineering' },
  { name: 'Redis Projects', slug: 'redis', category: 'Software Engineering' },
  { name: 'SQLite Projects', slug: 'sqlite', category: 'Software Engineering' },
  { name: 'Graph Databases', slug: 'graph-db', category: 'Software Engineering' },
  { name: 'Vector Databases', slug: 'vector-db', category: 'Software Engineering' },
  { name: 'Time-series Databases', slug: 'timeseries-db', category: 'Software Engineering' },
  { name: 'ORM / Query Builders', slug: 'orm', category: 'Software Engineering' },
  { name: 'Database Migrations', slug: 'db-migrations', category: 'Software Engineering' },
  { name: 'Data Pipelines', slug: 'data-pipelines', category: 'Software Engineering' },
  { name: 'ETL Tools', slug: 'etl', category: 'Software Engineering' },
  { name: 'Web Scraping', slug: 'scraping', category: 'Software Engineering' },
  { name: 'Automation Scripts', slug: 'automation', category: 'Software Engineering', popular: true },
  { name: 'Testing Frameworks', slug: 'testing', category: 'Software Engineering' },
  { name: 'E2E Testing', slug: 'e2e-testing', category: 'Software Engineering' },
  { name: 'Load Testing', slug: 'load-testing', category: 'Software Engineering' },
  { name: 'Monitoring Tools', slug: 'monitoring', category: 'Software Engineering' },
  { name: 'Observability', slug: 'observability', category: 'Software Engineering' },
  { name: 'Logging', slug: 'logging', category: 'Software Engineering' },
  { name: 'Analytics Tools', slug: 'analytics', category: 'Software Engineering' },
  { name: 'A/B Testing Tools', slug: 'ab-testing', category: 'Software Engineering' },
  { name: 'Feature Flags', slug: 'feature-flags', category: 'Software Engineering' },
  { name: 'Search Systems', slug: 'search-systems', category: 'Software Engineering' },
  { name: 'Elasticsearch Projects', slug: 'elasticsearch', category: 'Software Engineering' },
  { name: 'Full-Text Search', slug: 'full-text-search', category: 'Software Engineering' },
  { name: 'Recommendation Systems', slug: 'recsys', category: 'Software Engineering' },
  { name: 'Payment Systems', slug: 'payments', category: 'Software Engineering' },
  { name: 'Stripe Integration', slug: 'stripe', category: 'Software Engineering' },
  { name: 'Authentication', slug: 'auth', category: 'Software Engineering' },
  { name: 'OAuth Systems', slug: 'oauth', category: 'Software Engineering' },
  { name: 'JWT / Sessions', slug: 'jwt', category: 'Software Engineering' },
  { name: 'Cybersecurity', slug: 'cybersecurity', category: 'Software Engineering' },
  { name: 'Application Security', slug: 'appsec', category: 'Software Engineering' },
  { name: 'Penetration Testing', slug: 'pentest', category: 'Software Engineering' },
  { name: 'Bug Bounty', slug: 'bug-bounty', category: 'Software Engineering' },
  { name: 'Ethical Hacking', slug: 'ethical-hacking', category: 'Software Engineering' },
  { name: 'Cryptography', slug: 'cryptography', category: 'Software Engineering' },
  { name: 'Zero Knowledge Proofs', slug: 'zk-proofs', category: 'Software Engineering' },
  { name: 'Compilers', slug: 'compilers', category: 'Software Engineering' },
  { name: 'Interpreters', slug: 'interpreters', category: 'Software Engineering' },
  { name: 'Programming Languages', slug: 'programming-languages', category: 'Software Engineering' },
  { name: 'DSLs', slug: 'dsl', category: 'Software Engineering' },
  { name: 'Static Analysis', slug: 'static-analysis', category: 'Software Engineering' },
  { name: 'Linters', slug: 'linters', category: 'Software Engineering' },
  { name: 'Code Formatters', slug: 'formatters', category: 'Software Engineering' },
  { name: 'Package Managers', slug: 'package-managers', category: 'Software Engineering' },
  { name: 'Build Tools', slug: 'build-tools', category: 'Software Engineering' },
  { name: 'Bundlers', slug: 'bundlers', category: 'Software Engineering' },
  { name: 'Terminal Apps', slug: 'terminal-apps', category: 'Software Engineering' },
  { name: 'TUI Applications', slug: 'tui', category: 'Software Engineering' },
  { name: 'System Programming', slug: 'system-programming', category: 'Software Engineering' },
  { name: 'Kernel Development', slug: 'kernel-dev', category: 'Software Engineering' },
  { name: 'Operating Systems', slug: 'operating-systems', category: 'Software Engineering' },
  { name: 'Networking Tools', slug: 'networking', category: 'Software Engineering' },
  { name: 'VPN Systems', slug: 'vpn', category: 'Software Engineering' },
  { name: 'Proxy Servers', slug: 'proxy', category: 'Software Engineering' },
  { name: 'Load Balancers', slug: 'load-balancers', category: 'Software Engineering' },
  { name: 'Message Queues', slug: 'message-queues', category: 'Software Engineering' },
  { name: 'Event Streaming', slug: 'event-streaming', category: 'Software Engineering' },
  { name: 'Kafka Projects', slug: 'kafka', category: 'Software Engineering' },
  { name: 'Distributed Systems', slug: 'distributed-systems', category: 'Software Engineering' },
  { name: 'Consensus Algorithms', slug: 'consensus', category: 'Software Engineering' },
  { name: 'Peer-to-Peer', slug: 'p2p', category: 'Software Engineering' },
  { name: 'CDN Projects', slug: 'cdn', category: 'Software Engineering' },
  { name: 'Documentation Tools', slug: 'docs-tools', category: 'Software Engineering' },
  { name: 'Static Site Generators', slug: 'ssg', category: 'Software Engineering' },
  { name: 'Headless CMS', slug: 'headless-cms', category: 'Software Engineering' },

  // ─── AI / MACHINE LEARNING (65+) ───
  { name: 'AI / Machine Learning', slug: 'ai-ml', category: 'AI & Data', popular: true },
  { name: 'Deep Learning', slug: 'deep-learning', category: 'AI & Data', popular: true },
  { name: 'Neural Networks', slug: 'neural-networks', category: 'AI & Data' },
  { name: 'Computer Vision', slug: 'computer-vision', category: 'AI & Data', popular: true },
  { name: 'Image Recognition', slug: 'image-recognition', category: 'AI & Data' },
  { name: 'Object Detection', slug: 'object-detection', category: 'AI & Data' },
  { name: 'Image Segmentation', slug: 'image-segmentation', category: 'AI & Data' },
  { name: 'OCR', slug: 'ocr', category: 'AI & Data' },
  { name: 'Face Recognition', slug: 'face-recognition', category: 'AI & Data' },
  { name: 'Natural Language Processing', slug: 'nlp', category: 'AI & Data', popular: true, aliases: ['NLP'] },
  { name: 'Sentiment Analysis', slug: 'sentiment', category: 'AI & Data' },
  { name: 'Text Classification', slug: 'text-classification', category: 'AI & Data' },
  { name: 'Text Summarization', slug: 'summarization', category: 'AI & Data' },
  { name: 'Named Entity Recognition', slug: 'ner', category: 'AI & Data' },
  { name: 'Question Answering', slug: 'qa-systems', category: 'AI & Data' },
  { name: 'Speech Recognition', slug: 'speech-recognition', category: 'AI & Data' },
  { name: 'Speech Synthesis', slug: 'tts', category: 'AI & Data' },
  { name: 'Voice AI', slug: 'voice-ai', category: 'AI & Data' },
  { name: 'Generative AI', slug: 'gen-ai', category: 'AI & Data', popular: true },
  { name: 'LLM Applications', slug: 'llm-apps', category: 'AI & Data', popular: true },
  { name: 'Prompt Engineering', slug: 'prompt-engineering', category: 'AI & Data' },
  { name: 'AI Agents', slug: 'ai-agents', category: 'AI & Data', popular: true },
  { name: 'Autonomous Agents', slug: 'autonomous-agents', category: 'AI & Data' },
  { name: 'RAG Systems', slug: 'rag', category: 'AI & Data' },
  { name: 'AI Chatbots', slug: 'chatbots', category: 'AI & Data' },
  { name: 'AI Copilots', slug: 'copilots', category: 'AI & Data' },
  { name: 'AI Assistants', slug: 'ai-assistants', category: 'AI & Data' },
  { name: 'Multimodal AI', slug: 'multimodal', category: 'AI & Data' },
  { name: 'Image Generation', slug: 'image-generation', category: 'AI & Data' },
  { name: 'Video Generation', slug: 'video-generation', category: 'AI & Data' },
  { name: 'Music Generation', slug: 'music-gen', category: 'AI & Data' },
  { name: 'Code Generation', slug: 'code-gen', category: 'AI & Data' },
  { name: '3D Generation', slug: '3d-generation', category: 'AI & Data' },
  { name: 'Diffusion Models', slug: 'diffusion', category: 'AI & Data' },
  { name: 'Fine-tuning Models', slug: 'fine-tuning', category: 'AI & Data' },
  { name: 'Model Training', slug: 'model-training', category: 'AI & Data' },
  { name: 'MLOps', slug: 'mlops', category: 'AI & Data' },
  { name: 'Model Deployment', slug: 'model-deployment', category: 'AI & Data' },
  { name: 'Model Serving', slug: 'model-serving', category: 'AI & Data' },
  { name: 'Reinforcement Learning', slug: 'rl', category: 'AI & Data' },
  { name: 'Time Series ML', slug: 'timeseries-ml', category: 'AI & Data' },
  { name: 'Anomaly Detection', slug: 'anomaly-detection', category: 'AI & Data' },
  { name: 'Predictive Analytics', slug: 'predictive-analytics', category: 'AI & Data' },
  { name: 'Data Science', slug: 'data-science', category: 'AI & Data', popular: true },
  { name: 'Data Engineering', slug: 'data-engineering', category: 'AI & Data' },
  { name: 'Data Analysis', slug: 'data-analysis', category: 'AI & Data' },
  { name: 'Data Visualization', slug: 'data-viz', category: 'AI & Data' },
  { name: 'Business Intelligence', slug: 'bi', category: 'AI & Data' },
  { name: 'Big Data', slug: 'big-data', category: 'AI & Data' },
  { name: 'Data Mining', slug: 'data-mining', category: 'AI & Data' },
  { name: 'Feature Engineering', slug: 'feature-engineering', category: 'AI & Data' },
  { name: 'Synthetic Data', slug: 'synthetic-data', category: 'AI & Data' },
  { name: 'Data Labeling', slug: 'data-labeling', category: 'AI & Data' },
  { name: 'AI Safety', slug: 'ai-safety', category: 'AI & Data' },
  { name: 'AI Ethics', slug: 'ai-ethics', category: 'AI & Data' },
  { name: 'AI Alignment', slug: 'ai-alignment', category: 'AI & Data' },
  { name: 'Explainable AI', slug: 'xai', category: 'AI & Data' },
  { name: 'Federated Learning', slug: 'federated-learning', category: 'AI & Data' },
  { name: 'Edge AI', slug: 'edge-ai', category: 'AI & Data' },
  { name: 'AI Infrastructure', slug: 'ai-infra', category: 'AI & Data' },
  { name: 'Vector Search', slug: 'vector-search', category: 'AI & Data' },
  { name: 'Embeddings', slug: 'embeddings', category: 'AI & Data' },
  { name: 'Semantic Search', slug: 'semantic-search', category: 'AI & Data' },
  { name: 'Knowledge Graphs', slug: 'knowledge-graphs', category: 'AI & Data' },
  { name: 'Foundation Models', slug: 'foundation-models', category: 'AI & Data' },

  // ─── HARDWARE / MAKER (55+) ───
  { name: 'Hardware Projects', slug: 'hardware', category: 'Hardware & Maker', popular: true },
  { name: 'Arduino Projects', slug: 'arduino', category: 'Hardware & Maker', popular: true },
  { name: 'Raspberry Pi', slug: 'raspberry-pi', category: 'Hardware & Maker', popular: true },
  { name: 'ESP32 Projects', slug: 'esp32', category: 'Hardware & Maker' },
  { name: 'Microcontrollers', slug: 'microcontrollers', category: 'Hardware & Maker' },
  { name: 'Embedded Systems', slug: 'embedded', category: 'Hardware & Maker' },
  { name: 'IoT Projects', slug: 'iot', category: 'Hardware & Maker', popular: true },
  { name: 'Smart Home', slug: 'smart-home', category: 'Hardware & Maker' },
  { name: 'Home Automation', slug: 'home-automation', category: 'Hardware & Maker' },
  { name: 'Robotics', slug: 'robotics', category: 'Hardware & Maker', popular: true },
  { name: 'Autonomous Robots', slug: 'autonomous-robots', category: 'Hardware & Maker' },
  { name: 'Robot Arms', slug: 'robot-arms', category: 'Hardware & Maker' },
  { name: 'Humanoid Robots', slug: 'humanoids', category: 'Hardware & Maker' },
  { name: 'Swarm Robotics', slug: 'swarm-robotics', category: 'Hardware & Maker' },
  { name: 'ROS Projects', slug: 'ros', category: 'Hardware & Maker' },
  { name: 'Drones', slug: 'drones', category: 'Hardware & Maker' },
  { name: 'FPV Drones', slug: 'fpv-drones', category: 'Hardware & Maker' },
  { name: 'Racing Drones', slug: 'racing-drones', category: 'Hardware & Maker' },
  { name: 'Autonomous Drones', slug: 'autonomous-drones', category: 'Hardware & Maker' },
  { name: '3D Printing', slug: '3d-printing', category: 'Hardware & Maker', popular: true },
  { name: '3D Modeling', slug: '3d-modeling', category: 'Hardware & Maker' },
  { name: 'CAD Design', slug: 'cad', category: 'Hardware & Maker' },
  { name: 'CNC Projects', slug: 'cnc', category: 'Hardware & Maker' },
  { name: 'Laser Cutting', slug: 'laser-cutting', category: 'Hardware & Maker' },
  { name: 'PCB Design', slug: 'pcb-design', category: 'Hardware & Maker' },
  { name: 'Electronics', slug: 'electronics', category: 'Hardware & Maker' },
  { name: 'Analog Electronics', slug: 'analog', category: 'Hardware & Maker' },
  { name: 'Digital Electronics', slug: 'digital-electronics', category: 'Hardware & Maker' },
  { name: 'FPGA Projects', slug: 'fpga', category: 'Hardware & Maker' },
  { name: 'Chip Design', slug: 'chip-design', category: 'Hardware & Maker' },
  { name: 'Semiconductors', slug: 'semiconductors', category: 'Hardware & Maker' },
  { name: 'Wearables', slug: 'wearables', category: 'Hardware & Maker' },
  { name: 'Fitness Trackers', slug: 'fitness-trackers', category: 'Hardware & Maker' },
  { name: 'Smart Watches', slug: 'smart-watches', category: 'Hardware & Maker' },
  { name: 'Sensors', slug: 'sensors', category: 'Hardware & Maker' },
  { name: 'Environmental Sensors', slug: 'env-sensors', category: 'Hardware & Maker' },
  { name: 'Biosensors', slug: 'biosensors', category: 'Hardware & Maker' },
  { name: 'Actuators', slug: 'actuators', category: 'Hardware & Maker' },
  { name: 'Motors & Servos', slug: 'motors', category: 'Hardware & Maker' },
  { name: 'Mechatronics', slug: 'mechatronics', category: 'Hardware & Maker' },
  { name: 'Mechanical Engineering', slug: 'mech-eng', category: 'Hardware & Maker' },
  { name: 'DIY Electronics', slug: 'diy-electronics', category: 'Hardware & Maker' },
  { name: 'Hacker Boards', slug: 'hacker-boards', category: 'Hardware & Maker' },
  { name: 'Retro Computing', slug: 'retro-computing', category: 'Hardware & Maker' },
  { name: 'Custom Keyboards', slug: 'custom-keyboards', category: 'Hardware & Maker' },
  { name: 'Modular Synths', slug: 'modular-synths', category: 'Hardware & Maker' },
  { name: 'Musical Instruments', slug: 'instruments', category: 'Hardware & Maker' },
  { name: 'Audio Hardware', slug: 'audio-hardware', category: 'Hardware & Maker' },
  { name: 'AR/VR Hardware', slug: 'ar-vr-hw', category: 'Hardware & Maker' },
  { name: 'Haptics', slug: 'haptics', category: 'Hardware & Maker' },
  { name: 'Brain-Computer Interface', slug: 'bci', category: 'Hardware & Maker' },
  { name: 'Rocketry', slug: 'rocketry', category: 'Hardware & Maker' },
  { name: 'Satellites', slug: 'satellites', category: 'Hardware & Maker' },
  { name: 'CubeSats', slug: 'cubesats', category: 'Hardware & Maker' },
  { name: 'Space Hardware', slug: 'space-hw', category: 'Hardware & Maker' },

  // ─── CREATIVE / DESIGN (65+) ───
  { name: 'Design Systems', slug: 'design-systems', category: 'Creative', popular: true },
  { name: 'UI Design', slug: 'ui-design', category: 'Creative', popular: true },
  { name: 'UX Design', slug: 'ux-design', category: 'Creative', popular: true },
  { name: 'Product Design', slug: 'product-design', category: 'Creative', popular: true },
  { name: 'Interaction Design', slug: 'ixd', category: 'Creative' },
  { name: 'Visual Design', slug: 'visual-design', category: 'Creative' },
  { name: 'Graphic Design', slug: 'graphic-design', category: 'Creative' },
  { name: 'Web Design', slug: 'web-design', category: 'Creative' },
  { name: 'Icon Design', slug: 'icon-design', category: 'Creative' },
  { name: 'Illustration', slug: 'illustration', category: 'Creative' },
  { name: 'Digital Art', slug: 'digital-art', category: 'Creative' },
  { name: 'Traditional Art', slug: 'traditional-art', category: 'Creative' },
  { name: 'Concept Art', slug: 'concept-art', category: 'Creative' },
  { name: 'Character Design', slug: 'character-design', category: 'Creative' },
  { name: 'Environment Design', slug: 'environment-design', category: 'Creative' },
  { name: 'Typography', slug: 'typography', category: 'Creative' },
  { name: 'Font Design', slug: 'font-design', category: 'Creative' },
  { name: 'Branding', slug: 'branding', category: 'Creative' },
  { name: 'Logo Design', slug: 'logo-design', category: 'Creative' },
  { name: 'Motion Design', slug: 'motion-design', category: 'Creative' },
  { name: 'Animation', slug: 'animation', category: 'Creative' },
  { name: '2D Animation', slug: '2d-animation', category: 'Creative' },
  { name: '3D Animation', slug: '3d-animation', category: 'Creative' },
  { name: 'After Effects', slug: 'after-effects', category: 'Creative' },
  { name: 'Blender Projects', slug: 'blender', category: 'Creative' },
  { name: '3D Rendering', slug: '3d-rendering', category: 'Creative' },
  { name: 'VFX', slug: 'vfx', category: 'Creative' },
  { name: 'Video Editing', slug: 'video-editing', category: 'Creative' },
  { name: 'Film Making', slug: 'filmmaking', category: 'Creative' },
  { name: 'Documentary', slug: 'documentary', category: 'Creative' },
  { name: 'Short Films', slug: 'short-films', category: 'Creative' },
  { name: 'Cinematography', slug: 'cinematography', category: 'Creative' },
  { name: 'Photography', slug: 'photography', category: 'Creative' },
  { name: 'Photo Editing', slug: 'photo-editing', category: 'Creative' },
  { name: 'Music Production', slug: 'music-production', category: 'Creative' },
  { name: 'Sound Design', slug: 'sound-design', category: 'Creative' },
  { name: 'Audio Engineering', slug: 'audio-engineering', category: 'Creative' },
  { name: 'Podcast Production', slug: 'podcasting', category: 'Creative' },
  { name: 'Composition', slug: 'composition', category: 'Creative' },
  { name: 'Beat Making', slug: 'beat-making', category: 'Creative' },
  { name: 'Songwriting', slug: 'songwriting', category: 'Creative' },
  { name: 'Writing', slug: 'writing', category: 'Creative' },
  { name: 'Blogging', slug: 'blogging', category: 'Creative' },
  { name: 'Newsletter Writing', slug: 'newsletters', category: 'Creative' },
  { name: 'Technical Writing', slug: 'technical-writing', category: 'Creative' },
  { name: 'Copywriting', slug: 'copywriting', category: 'Creative' },
  { name: 'Fiction Writing', slug: 'fiction', category: 'Creative' },
  { name: 'Non-fiction Writing', slug: 'non-fiction', category: 'Creative' },
  { name: 'Poetry', slug: 'poetry', category: 'Creative' },
  { name: 'Screenwriting', slug: 'screenwriting', category: 'Creative' },
  { name: 'Comics / Manga', slug: 'comics', category: 'Creative' },
  { name: 'Webcomics', slug: 'webcomics', category: 'Creative' },
  { name: 'Zine Making', slug: 'zines', category: 'Creative' },
  { name: 'Print Design', slug: 'print-design', category: 'Creative' },
  { name: 'Book Design', slug: 'book-design', category: 'Creative' },
  { name: 'Fashion Design', slug: 'fashion-design', category: 'Creative' },
  { name: 'Textile Design', slug: 'textile', category: 'Creative' },
  { name: 'Interior Design', slug: 'interior-design', category: 'Creative' },
  { name: 'Architecture', slug: 'architecture', category: 'Creative' },
  { name: 'Landscape Design', slug: 'landscape', category: 'Creative' },
  { name: 'Industrial Design', slug: 'industrial-design', category: 'Creative' },
  { name: 'Sculpture', slug: 'sculpture', category: 'Creative' },
  { name: 'Ceramics', slug: 'ceramics', category: 'Creative' },
  { name: 'Woodworking', slug: 'woodworking', category: 'Creative' },
  { name: 'Metalworking', slug: 'metalworking', category: 'Creative' },
  { name: 'Generative Art', slug: 'generative-art', category: 'Creative' },
  { name: 'Creative Coding', slug: 'creative-coding', category: 'Creative' },
  { name: 'p5.js Projects', slug: 'p5js', category: 'Creative' },

  // ─── GAME DEVELOPMENT (45+) ───
  { name: 'Game Development', slug: 'game-dev', category: 'Game Dev', popular: true },
  { name: 'Indie Games', slug: 'indie-games', category: 'Game Dev', popular: true },
  { name: 'Unity Projects', slug: 'unity', category: 'Game Dev', popular: true },
  { name: 'Unreal Engine', slug: 'unreal', category: 'Game Dev' },
  { name: 'Godot Projects', slug: 'godot', category: 'Game Dev' },
  { name: 'Game Maker Studio', slug: 'gamemaker', category: 'Game Dev' },
  { name: 'Bevy Engine', slug: 'bevy', category: 'Game Dev' },
  { name: 'Phaser Games', slug: 'phaser', category: 'Game Dev' },
  { name: 'PICO-8', slug: 'pico8', category: 'Game Dev' },
  { name: '2D Games', slug: '2d-games', category: 'Game Dev' },
  { name: '3D Games', slug: '3d-games', category: 'Game Dev' },
  { name: 'Multiplayer Games', slug: 'multiplayer', category: 'Game Dev' },
  { name: 'MMO Development', slug: 'mmo', category: 'Game Dev' },
  { name: 'Battle Royale', slug: 'battle-royale', category: 'Game Dev' },
  { name: 'Roguelikes', slug: 'roguelikes', category: 'Game Dev' },
  { name: 'RPGs', slug: 'rpg', category: 'Game Dev' },
  { name: 'Strategy Games', slug: 'strategy-games', category: 'Game Dev' },
  { name: 'Puzzle Games', slug: 'puzzle-games', category: 'Game Dev' },
  { name: 'Platformers', slug: 'platformers', category: 'Game Dev' },
  { name: 'Racing Games', slug: 'racing-games', category: 'Game Dev' },
  { name: 'Simulation Games', slug: 'sim-games', category: 'Game Dev' },
  { name: 'City Builders', slug: 'city-builders', category: 'Game Dev' },
  { name: 'Sandbox Games', slug: 'sandbox', category: 'Game Dev' },
  { name: 'Card Games', slug: 'card-games', category: 'Game Dev' },
  { name: 'Board Games', slug: 'board-games', category: 'Game Dev' },
  { name: 'Tabletop Games', slug: 'tabletop', category: 'Game Dev' },
  { name: 'VR Games', slug: 'vr-games', category: 'Game Dev' },
  { name: 'AR Games', slug: 'ar-games', category: 'Game Dev' },
  { name: 'Mobile Games', slug: 'mobile-games', category: 'Game Dev' },
  { name: 'Web Games', slug: 'web-games', category: 'Game Dev' },
  { name: 'HTML5 Games', slug: 'html5-games', category: 'Game Dev' },
  { name: 'Cloud Gaming', slug: 'cloud-gaming', category: 'Game Dev' },
  { name: 'Web3 Games', slug: 'web3-gaming', category: 'Game Dev' },
  { name: 'Game AI', slug: 'game-ai', category: 'Game Dev' },
  { name: 'Procedural Generation', slug: 'procgen', category: 'Game Dev' },
  { name: 'Level Design', slug: 'level-design', category: 'Game Dev' },
  { name: 'Game Design', slug: 'game-design', category: 'Game Dev' },
  { name: 'Game Art', slug: 'game-art', category: 'Game Dev' },
  { name: 'Pixel Art', slug: 'pixel-art', category: 'Game Dev' },
  { name: 'Voxel Art', slug: 'voxel-art', category: 'Game Dev' },
  { name: 'Game Audio', slug: 'game-audio', category: 'Game Dev' },
  { name: 'Game Music', slug: 'game-music', category: 'Game Dev' },
  { name: 'Game Engines', slug: 'game-engines', category: 'Game Dev' },
  { name: 'Physics Engines', slug: 'physics-engines', category: 'Game Dev' },
  { name: 'Rendering Engines', slug: 'rendering-engines', category: 'Game Dev' },
  { name: 'Game Mods', slug: 'game-mods', category: 'Game Dev' },
  { name: 'Speedrunning Tools', slug: 'speedrunning', category: 'Game Dev' },

  // ─── OPEN SOURCE (35+) ───
  { name: 'Open Source', slug: 'open-source', category: 'Open Source', popular: true },
  { name: 'OSS Contributions', slug: 'oss-contributions', category: 'Open Source' },
  { name: 'Developer Libraries', slug: 'libraries', category: 'Open Source' },
  { name: 'JavaScript Libraries', slug: 'js-libs', category: 'Open Source' },
  { name: 'Python Libraries', slug: 'python-libs', category: 'Open Source' },
  { name: 'Rust Libraries', slug: 'rust-libs', category: 'Open Source' },
  { name: 'Go Packages', slug: 'go-packages', category: 'Open Source' },
  { name: 'TypeScript Libraries', slug: 'ts-libs', category: 'Open Source' },
  { name: 'React Components', slug: 'react-components', category: 'Open Source' },
  { name: 'Vue Components', slug: 'vue-components', category: 'Open Source' },
  { name: 'Svelte Components', slug: 'svelte-components', category: 'Open Source' },
  { name: 'CSS Frameworks', slug: 'css-frameworks', category: 'Open Source' },
  { name: 'Design Tools', slug: 'design-tools', category: 'Open Source' },
  { name: 'Figma Plugins', slug: 'figma-plugins', category: 'Open Source' },
  { name: 'Blender Add-ons', slug: 'blender-addons', category: 'Open Source' },
  { name: 'API Wrappers', slug: 'api-wrappers', category: 'Open Source' },
  { name: 'SDK Development', slug: 'sdk-dev', category: 'Open Source' },
  { name: 'Framework Development', slug: 'framework-dev', category: 'Open Source' },
  { name: 'Boilerplates', slug: 'boilerplates', category: 'Open Source' },
  { name: 'Starter Templates', slug: 'templates', category: 'Open Source' },
  { name: 'Themes', slug: 'themes', category: 'Open Source' },
  { name: 'Plugins', slug: 'plugins', category: 'Open Source' },
  { name: 'Awesome Lists', slug: 'awesome-lists', category: 'Open Source' },
  { name: 'Documentation Projects', slug: 'docs-projects', category: 'Open Source' },
  { name: 'Learning Resources', slug: 'learning-resources', category: 'Open Source' },
  { name: 'Code Examples', slug: 'code-examples', category: 'Open Source' },
  { name: 'Tutorials', slug: 'tutorials', category: 'Open Source' },
  { name: 'Coding Challenges', slug: 'coding-challenges', category: 'Open Source' },
  { name: 'Algorithms', slug: 'algorithms', category: 'Open Source' },
  { name: 'Data Structures', slug: 'data-structures', category: 'Open Source' },
  { name: 'LeetCode Solutions', slug: 'leetcode', category: 'Open Source' },
  { name: 'Interview Prep', slug: 'interview-prep', category: 'Open Source' },
  { name: 'DevOps Tools OSS', slug: 'devops-oss', category: 'Open Source' },
  { name: 'Testing Utilities', slug: 'test-utils', category: 'Open Source' },
  { name: 'Static Analysis Tools', slug: 'static-analysis-oss', category: 'Open Source' },

  // ─── RESEARCH / ACADEMIC (45+) ───
  { name: 'Research', slug: 'research', category: 'Research & Academic' },
  { name: 'Academic Research', slug: 'academic-research', category: 'Research & Academic' },
  { name: 'PhD Research', slug: 'phd-research', category: 'Research & Academic' },
  { name: 'Master Thesis', slug: 'thesis', category: 'Research & Academic' },
  { name: 'Undergraduate Research', slug: 'undergrad-research', category: 'Research & Academic' },
  { name: 'Research Papers', slug: 'papers', category: 'Research & Academic' },
  { name: 'Literature Review', slug: 'lit-review', category: 'Research & Academic' },
  { name: 'AI Research', slug: 'ai-research', category: 'Research & Academic', popular: true },
  { name: 'ML Research', slug: 'ml-research', category: 'Research & Academic' },
  { name: 'Computer Science Research', slug: 'cs-research', category: 'Research & Academic' },
  { name: 'HCI Research', slug: 'hci', category: 'Research & Academic' },
  { name: 'Systems Research', slug: 'systems-research', category: 'Research & Academic' },
  { name: 'Theory Research', slug: 'theory', category: 'Research & Academic' },
  { name: 'Cryptography Research', slug: 'crypto-research', category: 'Research & Academic' },
  { name: 'Security Research', slug: 'security-research', category: 'Research & Academic' },
  { name: 'Bioinformatics', slug: 'bioinformatics', category: 'Research & Academic' },
  { name: 'Computational Biology', slug: 'comp-bio', category: 'Research & Academic' },
  { name: 'Genomics Research', slug: 'genomics-research', category: 'Research & Academic' },
  { name: 'Neuroscience', slug: 'neuroscience', category: 'Research & Academic' },
  { name: 'Cognitive Science', slug: 'cog-sci', category: 'Research & Academic' },
  { name: 'Chemistry Research', slug: 'chemistry', category: 'Research & Academic' },
  { name: 'Physics Research', slug: 'physics', category: 'Research & Academic' },
  { name: 'Quantum Computing', slug: 'quantum-computing', category: 'Research & Academic' },
  { name: 'Materials Science', slug: 'materials', category: 'Research & Academic' },
  { name: 'Astrophysics', slug: 'astrophysics', category: 'Research & Academic' },
  { name: 'Mathematics', slug: 'mathematics', category: 'Research & Academic' },
  { name: 'Applied Math', slug: 'applied-math', category: 'Research & Academic' },
  { name: 'Statistics Research', slug: 'stats-research', category: 'Research & Academic' },
  { name: 'Economics Research', slug: 'econ-research', category: 'Research & Academic' },
  { name: 'Social Science', slug: 'social-science', category: 'Research & Academic' },
  { name: 'Psychology', slug: 'psychology', category: 'Research & Academic' },
  { name: 'Behavioral Research', slug: 'behavioral', category: 'Research & Academic' },
  { name: 'Linguistics', slug: 'linguistics', category: 'Research & Academic' },
  { name: 'Anthropology', slug: 'anthropology', category: 'Research & Academic' },
  { name: 'History Research', slug: 'history', category: 'Research & Academic' },
  { name: 'Philosophy', slug: 'philosophy', category: 'Research & Academic' },
  { name: 'Data Studies', slug: 'data-studies', category: 'Research & Academic' },
  { name: 'Reproducibility Projects', slug: 'reproducibility', category: 'Research & Academic' },
  { name: 'Meta-Analysis', slug: 'meta-analysis', category: 'Research & Academic' },
  { name: 'Survey Research', slug: 'surveys', category: 'Research & Academic' },
  { name: 'Field Studies', slug: 'field-studies', category: 'Research & Academic' },
  { name: 'Case Studies', slug: 'case-studies', category: 'Research & Academic' },
  { name: 'Whitepapers', slug: 'whitepapers', category: 'Research & Academic' },
  { name: 'Open Research', slug: 'open-research', category: 'Research & Academic' },
  { name: 'Citizen Science', slug: 'citizen-science', category: 'Research & Academic' },

  // ─── COMMUNITY / SOCIAL IMPACT (35+) ───
  { name: 'Community Projects', slug: 'community-projects', category: 'Community & Impact' },
  { name: 'Social Impact', slug: 'social-impact', category: 'Community & Impact', popular: true },
  { name: 'Nonprofit Tech', slug: 'nonprofit', category: 'Community & Impact' },
  { name: 'Civic Tech', slug: 'civic-tech', category: 'Community & Impact' },
  { name: 'Volunteering Platforms', slug: 'volunteering', category: 'Community & Impact' },
  { name: 'Fundraising Tools', slug: 'fundraising', category: 'Community & Impact' },
  { name: 'Charity Platforms', slug: 'charity', category: 'Community & Impact' },
  { name: 'Mutual Aid', slug: 'mutual-aid', category: 'Community & Impact' },
  { name: 'Refugee Support', slug: 'refugee-tech', category: 'Community & Impact' },
  { name: 'Homelessness', slug: 'homelessness', category: 'Community & Impact' },
  { name: 'Food Security', slug: 'food-security', category: 'Community & Impact' },
  { name: 'Education Access', slug: 'edu-access', category: 'Community & Impact' },
  { name: 'Digital Literacy', slug: 'digital-literacy', category: 'Community & Impact' },
  { name: 'Accessibility', slug: 'accessibility', category: 'Community & Impact', popular: true, aliases: ['a11y'] },
  { name: 'Assistive Technology', slug: 'assistive-tech', category: 'Community & Impact' },
  { name: 'Sign Language', slug: 'sign-language', category: 'Community & Impact' },
  { name: 'Disability Rights', slug: 'disability-rights', category: 'Community & Impact' },
  { name: 'LGBTQ+ Support', slug: 'lgbtq', category: 'Community & Impact' },
  { name: 'Mental Health', slug: 'mental-health', category: 'Community & Impact' },
  { name: 'Suicide Prevention', slug: 'suicide-prevention', category: 'Community & Impact' },
  { name: 'Human Rights', slug: 'human-rights', category: 'Community & Impact' },
  { name: 'Climate Action', slug: 'climate-action', category: 'Community & Impact', popular: true },
  { name: 'Sustainability', slug: 'sustainability', category: 'Community & Impact' },
  { name: 'Environmental Protection', slug: 'environment', category: 'Community & Impact' },
  { name: 'Ocean Conservation', slug: 'ocean-conservation', category: 'Community & Impact' },
  { name: 'Wildlife Protection', slug: 'wildlife', category: 'Community & Impact' },
  { name: 'Animal Welfare', slug: 'animal-welfare', category: 'Community & Impact' },
  { name: 'Disaster Response', slug: 'disaster-response', category: 'Community & Impact' },
  { name: 'Emergency Tech', slug: 'emergency-tech', category: 'Community & Impact' },
  { name: 'Public Health', slug: 'public-health', category: 'Community & Impact' },
  { name: 'Global Health', slug: 'global-health', category: 'Community & Impact' },
  { name: 'Elderly Care', slug: 'elderly-care', category: 'Community & Impact' },
  { name: 'Kids Education', slug: 'kids-education', category: 'Community & Impact' },
  { name: 'Local Community', slug: 'local-community', category: 'Community & Impact' },
  { name: 'Grassroots Organizing', slug: 'grassroots', category: 'Community & Impact' },

  // ─── WEB3 / BLOCKCHAIN (40+) ───
  { name: 'Web3', slug: 'web3', category: 'Web3 & Blockchain', popular: true },
  { name: 'Blockchain', slug: 'blockchain', category: 'Web3 & Blockchain', popular: true },
  { name: 'Cryptocurrency', slug: 'crypto', category: 'Web3 & Blockchain' },
  { name: 'DeFi Projects', slug: 'defi', category: 'Web3 & Blockchain', popular: true },
  { name: 'NFTs', slug: 'nft', category: 'Web3 & Blockchain' },
  { name: 'Smart Contracts', slug: 'smart-contracts', category: 'Web3 & Blockchain' },
  { name: 'Solidity', slug: 'solidity', category: 'Web3 & Blockchain' },
  { name: 'Rust Smart Contracts', slug: 'rust-contracts', category: 'Web3 & Blockchain' },
  { name: 'Ethereum Projects', slug: 'ethereum', category: 'Web3 & Blockchain' },
  { name: 'Solana Projects', slug: 'solana', category: 'Web3 & Blockchain' },
  { name: 'Polygon Projects', slug: 'polygon', category: 'Web3 & Blockchain' },
  { name: 'Base Projects', slug: 'base', category: 'Web3 & Blockchain' },
  { name: 'Arbitrum Projects', slug: 'arbitrum', category: 'Web3 & Blockchain' },
  { name: 'Optimism Projects', slug: 'optimism', category: 'Web3 & Blockchain' },
  { name: 'Layer 2 Solutions', slug: 'l2', category: 'Web3 & Blockchain' },
  { name: 'Rollups', slug: 'rollups', category: 'Web3 & Blockchain' },
  { name: 'ZK Rollups', slug: 'zk-rollups', category: 'Web3 & Blockchain' },
  { name: 'DAO Tools', slug: 'dao-tools', category: 'Web3 & Blockchain' },
  { name: 'Governance Systems', slug: 'governance', category: 'Web3 & Blockchain' },
  { name: 'DEX Aggregators', slug: 'dex-aggregators', category: 'Web3 & Blockchain' },
  { name: 'Yield Farming', slug: 'yield-farming', category: 'Web3 & Blockchain' },
  { name: 'Lending Protocols', slug: 'lending-protocols', category: 'Web3 & Blockchain' },
  { name: 'Stablecoins', slug: 'stablecoins', category: 'Web3 & Blockchain' },
  { name: 'Prediction Markets', slug: 'prediction-markets', category: 'Web3 & Blockchain' },
  { name: 'On-Chain Analytics', slug: 'onchain-analytics', category: 'Web3 & Blockchain' },
  { name: 'Wallet Development', slug: 'wallets', category: 'Web3 & Blockchain' },
  { name: 'Multi-sig Wallets', slug: 'multisig', category: 'Web3 & Blockchain' },
  { name: 'Bridges', slug: 'bridges', category: 'Web3 & Blockchain' },
  { name: 'Oracles', slug: 'oracles', category: 'Web3 & Blockchain' },
  { name: 'Chainlink Projects', slug: 'chainlink', category: 'Web3 & Blockchain' },
  { name: 'IPFS Projects', slug: 'ipfs', category: 'Web3 & Blockchain' },
  { name: 'Decentralized Storage', slug: 'decentralized-storage', category: 'Web3 & Blockchain' },
  { name: 'Arweave', slug: 'arweave', category: 'Web3 & Blockchain' },
  { name: 'Farcaster', slug: 'farcaster', category: 'Web3 & Blockchain' },
  { name: 'Lens Protocol', slug: 'lens', category: 'Web3 & Blockchain' },
  { name: 'Social Tokens', slug: 'social-tokens', category: 'Web3 & Blockchain' },
  { name: 'Token Gating', slug: 'token-gating', category: 'Web3 & Blockchain' },
  { name: 'Web3 Auth', slug: 'web3-auth', category: 'Web3 & Blockchain' },
  { name: 'MEV Research', slug: 'mev', category: 'Web3 & Blockchain' },
  { name: 'Zero Knowledge Applications', slug: 'zk-apps', category: 'Web3 & Blockchain' },

  // ─── SIDE / HOBBY (40+) ───
  { name: 'Side Projects', slug: 'side-projects', category: 'Side & Hobby', popular: true },
  { name: 'Weekend Projects', slug: 'weekend-projects', category: 'Side & Hobby' },
  { name: 'Learning Projects', slug: 'learning-projects', category: 'Side & Hobby', popular: true },
  { name: 'Personal Tools', slug: 'personal-tools', category: 'Side & Hobby' },
  { name: 'Scratch Your Itch', slug: 'scratch-itch', category: 'Side & Hobby' },
  { name: 'Portfolio Projects', slug: 'portfolio', category: 'Side & Hobby', popular: true },
  { name: 'Demo Projects', slug: 'demos', category: 'Side & Hobby' },
  { name: 'Experiments', slug: 'experiments', category: 'Side & Hobby' },
  { name: 'Fun Projects', slug: 'fun-projects', category: 'Side & Hobby' },
  { name: 'Silly Projects', slug: 'silly', category: 'Side & Hobby' },
  { name: 'Meme Projects', slug: 'memes', category: 'Side & Hobby' },
  { name: 'Curiosity Projects', slug: 'curiosity', category: 'Side & Hobby' },
  { name: 'Prototypes', slug: 'prototypes', category: 'Side & Hobby' },
  { name: 'MVPs', slug: 'mvp', category: 'Side & Hobby' },
  { name: 'Coding Bootcamps', slug: 'bootcamp', category: 'Side & Hobby' },
  { name: 'Class Projects', slug: 'class-projects', category: 'Side & Hobby' },
  { name: 'School Projects', slug: 'school-projects', category: 'Side & Hobby' },
  { name: 'College Projects', slug: 'college-projects', category: 'Side & Hobby' },
  { name: 'Hackathon Builds', slug: 'hackathon', category: 'Side & Hobby', popular: true },
  { name: 'Game Jams', slug: 'game-jams', category: 'Side & Hobby' },
  { name: 'Challenge Projects', slug: 'challenges', category: 'Side & Hobby' },
  { name: '100 Days of Code', slug: '100-days-of-code', category: 'Side & Hobby' },
  { name: 'Advent of Code', slug: 'advent-of-code', category: 'Side & Hobby' },
  { name: 'Build in Public', slug: 'build-in-public', category: 'Side & Hobby', popular: true },
  { name: 'Automation Hobbies', slug: 'automation-hobbies', category: 'Side & Hobby' },
  { name: 'Home Lab', slug: 'homelab', category: 'Side & Hobby' },
  { name: 'Self-Hosted', slug: 'self-hosted', category: 'Side & Hobby' },
  { name: 'Docker Compose', slug: 'docker-compose', category: 'Side & Hobby' },
  { name: 'Digital Gardens', slug: 'digital-gardens', category: 'Side & Hobby' },
  { name: 'Personal Websites', slug: 'personal-sites', category: 'Side & Hobby' },
  { name: 'Blog Engines', slug: 'blog-engines', category: 'Side & Hobby' },
  { name: 'Newsletter Systems', slug: 'newsletter-systems', category: 'Side & Hobby' },
  { name: 'Todo Apps', slug: 'todo-apps', category: 'Side & Hobby' },
  { name: 'Note-Taking Apps', slug: 'note-taking', category: 'Side & Hobby' },
  { name: 'Productivity Tools', slug: 'productivity-tools', category: 'Side & Hobby' },
  { name: 'Habit Trackers', slug: 'habit-trackers', category: 'Side & Hobby' },
  { name: 'Journaling Apps', slug: 'journaling', category: 'Side & Hobby' },
  { name: 'Mini SaaS', slug: 'mini-saas', category: 'Side & Hobby' },
  { name: 'Indie Hacker Projects', slug: 'indie-hacker', category: 'Side & Hobby' },
  { name: 'Bootstrapped Projects', slug: 'bootstrapped', category: 'Side & Hobby' },
  { name: 'Solopreneur Projects', slug: 'solopreneur', category: 'Side & Hobby' },
]

// ─── HELPERS ───

export function getProjectCategories(): string[] {
  const set = new Set<string>()
  PROJECT_DOMAINS.forEach(d => set.add(d.category))
  return Array.from(set).sort()
}

export function searchProjectDomains(query: string, limit = 15): ProjectDomain[] {
  if (!query || query.length < 1) return []
  const q = query.toLowerCase().trim()

  const startsWith: ProjectDomain[] = []
  const contains: ProjectDomain[] = []
  const aliasMatch: ProjectDomain[] = []

  for (const d of PROJECT_DOMAINS) {
    const nameLower = d.name.toLowerCase()
    if (nameLower.startsWith(q)) {
      startsWith.push(d)
    } else if (nameLower.includes(q)) {
      contains.push(d)
    } else if (d.aliases?.some(a => a.toLowerCase().includes(q))) {
      aliasMatch.push(d)
    }
  }

  return [...startsWith, ...contains, ...aliasMatch].slice(0, limit)
}

export function getPopularProjectDomains(limit = 20): ProjectDomain[] {
  return PROJECT_DOMAINS.filter(d => d.popular).slice(0, limit)
}