export interface SubCategory {
  id: string
  label: string
}

export interface Sector {
  id: string
  label: string
  icon: string
  color: string
  subCategories: SubCategory[]
}

export const SECTORS: Sector[] = [
  {
    id: 'technology',
    label: 'Technology',
    icon: 'Cpu',
    color: 'blue',
    subCategories: [
      { id: 'saas', label: 'SaaS' },
      { id: 'ai-ml', label: 'AI / Machine Learning' },
      { id: 'devtools', label: 'Developer Tools' },
      { id: 'cybersecurity', label: 'Cybersecurity' },
      { id: 'cloud', label: 'Cloud Infrastructure' },
      { id: 'blockchain', label: 'Blockchain / Web3' },
      { id: 'iot', label: 'IoT / Hardware' },
      { id: 'arvr', label: 'AR / VR / Metaverse' },
      { id: 'data', label: 'Data & Analytics' },
      { id: 'robotics', label: 'Robotics' },
      { id: 'quantum', label: 'Quantum Computing' },
      { id: 'telecom', label: 'Telecommunications' },
      { id: 'semiconductor', label: 'Semiconductors' },
      { id: 'gaming', label: 'Gaming' },
      { id: 'open-source', label: 'Open Source' },
    ]
  },
  {
    id: 'healthcare',
    label: 'Healthcare & Life Sciences',
    icon: 'HeartPulse',
    color: 'red',
    subCategories: [
      { id: 'healthtech', label: 'HealthTech' },
      { id: 'biotech', label: 'Biotech' },
      { id: 'pharma', label: 'Pharmaceuticals' },
      { id: 'meddevice', label: 'Medical Devices' },
      { id: 'telemedicine', label: 'Telemedicine' },
      { id: 'mental-health', label: 'Mental Health' },
      { id: 'fitness', label: 'Fitness & Wellness' },
      { id: 'diagnostics', label: 'Diagnostics' },
      { id: 'clinical-research', label: 'Clinical Research' },
      { id: 'elder-care', label: 'Elder Care' },
      { id: 'nutrition', label: 'Nutrition' },
      { id: 'dental', label: 'Dental' },
      { id: 'veterinary', label: 'Veterinary' },
      { id: 'ayurveda', label: 'Ayurveda / Traditional Medicine' },
    ]
  },
  {
    id: 'finance',
    label: 'Finance & Insurance',
    icon: 'DollarSign',
    color: 'green',
    subCategories: [
      { id: 'fintech', label: 'FinTech' },
      { id: 'banking', label: 'Banking' },
      { id: 'insurance', label: 'InsurTech' },
      { id: 'payments', label: 'Payments' },
      { id: 'lending', label: 'Lending' },
      { id: 'wealth', label: 'Wealth Management' },
      { id: 'crypto', label: 'Cryptocurrency' },
      { id: 'neobank', label: 'Neo Banking' },
      { id: 'regtech', label: 'RegTech' },
      { id: 'accounting', label: 'Accounting' },
      { id: 'tax', label: 'Tax Services' },
      { id: 'microfinance', label: 'Microfinance' },
    ]
  },
  {
    id: 'education',
    label: 'Education',
    icon: 'GraduationCap',
    color: 'indigo',
    subCategories: [
      { id: 'edtech', label: 'EdTech' },
      { id: 'lms', label: 'Learning Management' },
      { id: 'tutoring', label: 'Tutoring' },
      { id: 'skill-dev', label: 'Skill Development' },
      { id: 'test-prep', label: 'Test Prep' },
      { id: 'language', label: 'Language Learning' },
      { id: 'k12', label: 'K-12 Education' },
      { id: 'higher-ed', label: 'Higher Education' },
      { id: 'corporate-training', label: 'Corporate Training' },
      { id: 'coaching', label: 'Coaching Institute' },
      { id: 'publishing', label: 'Educational Publishing' },
    ]
  },
  {
    id: 'ecommerce',
    label: 'E-Commerce & Retail',
    icon: 'ShoppingBag',
    color: 'orange',
    subCategories: [
      { id: 'marketplace', label: 'Marketplace' },
      { id: 'd2c', label: 'D2C Brand' },
      { id: 'b2b-ecom', label: 'B2B E-Commerce' },
      { id: 'grocery', label: 'Grocery Delivery' },
      { id: 'fashion', label: 'Fashion & Apparel' },
      { id: 'electronics', label: 'Electronics' },
      { id: 'furniture', label: 'Furniture & Home' },
      { id: 'beauty', label: 'Beauty & Personal Care' },
      { id: 'jewelry', label: 'Jewelry' },
      { id: 'pet', label: 'Pet Products' },
      { id: 'sports-retail', label: 'Sports Equipment' },
      { id: 'luxury', label: 'Luxury Goods' },
      { id: 'secondhand', label: 'Resale / Second-hand' },
      { id: 'subscription', label: 'Subscription Box' },
    ]
  },
  {
    id: 'food',
    label: 'Food & Beverage',
    icon: 'UtensilsCrossed',
    color: 'amber',
    subCategories: [
      { id: 'restaurant', label: 'Restaurant' },
      { id: 'restaurant-chain', label: 'Restaurant Chain' },
      { id: 'cloud-kitchen', label: 'Cloud Kitchen' },
      { id: 'cafe', label: 'Café / Coffee Shop' },
      { id: 'bakery', label: 'Bakery' },
      { id: 'food-delivery', label: 'Food Delivery' },
      { id: 'food-processing', label: 'Food Processing' },
      { id: 'beverage', label: 'Beverage Brand' },
      { id: 'organic', label: 'Organic Food' },
      { id: 'food-tech', label: 'FoodTech' },
      { id: 'catering', label: 'Catering' },
      { id: 'meal-kit', label: 'Meal Kit' },
      { id: 'ice-cream', label: 'Ice Cream / Desserts' },
      { id: 'snacks', label: 'Snack Brand' },
      { id: 'dairy', label: 'Dairy' },
      { id: 'street-food', label: 'Street Food / Dhaba' },
    ]
  },
  {
    id: 'manufacturing',
    label: 'Manufacturing & Industrial',
    icon: 'Factory',
    color: 'gray',
    subCategories: [
      { id: 'heavy-manufacturing', label: 'Heavy Manufacturing' },
      { id: 'light-manufacturing', label: 'Light Manufacturing' },
      { id: 'textiles', label: 'Textiles & Garments' },
      { id: 'chemicals', label: 'Chemicals' },
      { id: 'steel', label: 'Steel & Metals' },
      { id: 'plastics', label: 'Plastics / Packaging' },
      { id: 'electronics-mfg', label: 'Electronics Manufacturing' },
      { id: 'auto-parts', label: 'Auto Parts' },
      { id: 'furniture-mfg', label: 'Furniture Manufacturing' },
      { id: 'printing', label: 'Printing' },
      { id: 'ceramics', label: 'Ceramics / Glass' },
      { id: 'paper', label: 'Paper & Pulp' },
      { id: 'tools', label: 'Tools & Equipment' },
    ]
  },
  {
    id: 'construction',
    label: 'Construction & Real Estate',
    icon: 'Building2',
    color: 'stone',
    subCategories: [
      { id: 'residential', label: 'Residential Construction' },
      { id: 'commercial-construction', label: 'Commercial Construction' },
      { id: 'proptech', label: 'PropTech' },
      { id: 'real-estate', label: 'Real Estate Development' },
      { id: 'infrastructure', label: 'Infrastructure' },
      { id: 'interior-design', label: 'Interior Design' },
      { id: 'architecture', label: 'Architecture Firm' },
      { id: 'coworking', label: 'Co-working Space' },
      { id: 'property-mgmt', label: 'Property Management' },
      { id: 'home-services', label: 'Home Services' },
    ]
  },
  {
    id: 'transport',
    label: 'Transportation & Logistics',
    icon: 'Truck',
    color: 'cyan',
    subCategories: [
      { id: 'ride-sharing', label: 'Ride Sharing' },
      { id: 'delivery', label: 'Last-mile Delivery' },
      { id: 'freight', label: 'Freight / Trucking' },
      { id: 'shipping', label: 'Shipping / Maritime' },
      { id: 'airlines', label: 'Airlines / Aviation' },
      { id: 'ev', label: 'Electric Vehicles' },
      { id: 'autonomous', label: 'Autonomous Vehicles' },
      { id: 'fleet', label: 'Fleet Management' },
      { id: 'warehouse', label: 'Warehousing' },
      { id: 'supply-chain', label: 'Supply Chain' },
      { id: 'railways', label: 'Railways' },
      { id: 'drone-delivery', label: 'Drone Delivery' },
    ]
  },
  {
    id: 'energy',
    label: 'Energy & Environment',
    icon: 'Zap',
    color: 'yellow',
    subCategories: [
      { id: 'solar', label: 'Solar Energy' },
      { id: 'wind', label: 'Wind Energy' },
      { id: 'cleantech', label: 'CleanTech' },
      { id: 'ev-charging', label: 'EV Charging' },
      { id: 'waste', label: 'Waste Management' },
      { id: 'water', label: 'Water Technology' },
      { id: 'carbon', label: 'Carbon Credits' },
      { id: 'nuclear', label: 'Nuclear' },
      { id: 'oil-gas', label: 'Oil & Gas' },
      { id: 'green-hydrogen', label: 'Green Hydrogen' },
      { id: 'recycling', label: 'Recycling' },
    ]
  },
  {
    id: 'agriculture',
    label: 'Agriculture & Allied',
    icon: 'Wheat',
    color: 'lime',
    subCategories: [
      { id: 'agritech', label: 'AgriTech' },
      { id: 'farming', label: 'Farming / Plantation' },
      { id: 'dairy-farm', label: 'Dairy Farm' },
      { id: 'poultry', label: 'Poultry' },
      { id: 'fisheries', label: 'Fisheries / Aquaculture' },
      { id: 'agri-marketplace', label: 'Agri Marketplace' },
      { id: 'fertilizer', label: 'Fertilizers / Pesticides' },
      { id: 'farm-equipment', label: 'Farm Equipment' },
      { id: 'organic-farming', label: 'Organic Farming' },
      { id: 'forestry', label: 'Forestry' },
      { id: 'horticulture', label: 'Horticulture / Floriculture' },
    ]
  },
  {
    id: 'media',
    label: 'Media & Entertainment',
    icon: 'Film',
    color: 'pink',
    subCategories: [
      { id: 'media-tech', label: 'Media Tech' },
      { id: 'ott', label: 'OTT / Streaming' },
      { id: 'music', label: 'Music' },
      { id: 'film', label: 'Film Production' },
      { id: 'news', label: 'News / Journalism' },
      { id: 'publishing', label: 'Publishing' },
      { id: 'podcast', label: 'Podcast' },
      { id: 'events', label: 'Events / Concerts' },
      { id: 'sports', label: 'Sports' },
      { id: 'esports', label: 'Esports' },
      { id: 'creator-economy', label: 'Creator Economy' },
      { id: 'advertising', label: 'Advertising' },
      { id: 'pr-agency', label: 'PR / Marketing Agency' },
    ]
  },
  {
    id: 'services',
    label: 'Professional Services',
    icon: 'Briefcase',
    color: 'slate',
    subCategories: [
      { id: 'consulting', label: 'Management Consulting' },
      { id: 'legal', label: 'Legal Services / LegalTech' },
      { id: 'hr-services', label: 'HR / Staffing' },
      { id: 'it-services', label: 'IT Services' },
      { id: 'design-agency', label: 'Design Agency' },
      { id: 'marketing-agency', label: 'Marketing Agency' },
      { id: 'ca-firm', label: 'CA / Accounting Firm' },
      { id: 'freelance-platform', label: 'Freelance Platform' },
      { id: 'security', label: 'Security Services' },
      { id: 'cleaning', label: 'Cleaning Services' },
      { id: 'maintenance', label: 'Maintenance / AMC' },
      { id: 'printing-services', label: 'Printing Services' },
    ]
  },
  {
    id: 'hospitality',
    label: 'Hospitality & Travel',
    icon: 'Hotel',
    color: 'teal',
    subCategories: [
      { id: 'hotel', label: 'Hotel / Resort' },
      { id: 'homestay', label: 'Homestay / B&B' },
      { id: 'travel-tech', label: 'Travel Tech' },
      { id: 'tour-operator', label: 'Tour Operator' },
      { id: 'travel-agency', label: 'Travel Agency' },
      { id: 'adventure', label: 'Adventure Tourism' },
      { id: 'medical-tourism', label: 'Medical Tourism' },
      { id: 'wedding-venue', label: 'Wedding / Event Venue' },
    ]
  },
  {
    id: 'social',
    label: 'Social Impact & Non-Profit',
    icon: 'Heart',
    color: 'rose',
    subCategories: [
      { id: 'ngo', label: 'NGO / Non-Profit' },
      { id: 'social-enterprise', label: 'Social Enterprise' },
      { id: 'impact-investing', label: 'Impact Investing' },
      { id: 'civic-tech', label: 'Civic Tech' },
      { id: 'disability', label: 'Disability / Accessibility' },
      { id: 'gender', label: 'Gender Equality' },
      { id: 'rural-dev', label: 'Rural Development' },
      { id: 'disaster', label: 'Disaster Relief' },
    ]
  },
  {
    id: 'defense',
    label: 'Defense & Space',
    icon: 'Shield',
    color: 'zinc',
    subCategories: [
      { id: 'defense-tech', label: 'Defense Tech' },
      { id: 'spacetech', label: 'Space Tech' },
      { id: 'surveillance', label: 'Surveillance' },
      { id: 'drones', label: 'Drones / UAV' },
      { id: 'naval', label: 'Naval / Maritime Defense' },
      { id: 'satellite', label: 'Satellite' },
      { id: 'ammunition', label: 'Arms & Ammunition' },
      { id: 'simulation', label: 'Simulation & Training' },
    ]
  },
  {
    id: 'government',
    label: 'Government & Public Sector',
    icon: 'Landmark',
    color: 'neutral',
    subCategories: [
      { id: 'govtech', label: 'GovTech' },
      { id: 'e-governance', label: 'E-Governance' },
      { id: 'smart-city', label: 'Smart City' },
      { id: 'public-infra', label: 'Public Infrastructure' },
      { id: 'digital-id', label: 'Digital Identity' },
    ]
  },
  {
    id: 'fashion',
    label: 'Fashion & Lifestyle',
    icon: 'Shirt',
    color: 'fuchsia',
    subCategories: [
      { id: 'apparel', label: 'Apparel Brand' },
      { id: 'footwear', label: 'Footwear' },
      { id: 'accessories', label: 'Accessories' },
      { id: 'cosmetics', label: 'Cosmetics / Beauty' },
      { id: 'eyewear', label: 'Eyewear' },
      { id: 'ethnic', label: 'Ethnic Wear' },
      { id: 'sustainable-fashion', label: 'Sustainable Fashion' },
      { id: 'tailoring', label: 'Tailoring / Custom' },
    ]
  },
  {
    id: 'automotive',
    label: 'Automotive',
    icon: 'Car',
    color: 'sky',
    subCategories: [
      { id: 'auto-oem', label: 'Vehicle Manufacturer' },
      { id: 'auto-parts', label: 'Auto Parts / Components' },
      { id: 'car-rental', label: 'Car Rental' },
      { id: 'auto-repair', label: 'Auto Repair / Service' },
      { id: 'used-cars', label: 'Used Cars Marketplace' },
      { id: 'ev-auto', label: 'Electric Vehicles' },
      { id: 'two-wheeler', label: 'Two Wheeler' },
      { id: 'auto-tech', label: 'Auto Tech' },
    ]
  },
  {
    id: 'other',
    label: 'Other',
    icon: 'Grid',
    color: 'neutral',
    subCategories: [
      { id: 'custom', label: 'Custom / Not Listed' },
    ]
  },
]

export const STAGES = [
  { id: 'idea', label: 'Idea Stage', color: 'bg-blue-500/10 text-blue-500 border-blue-500/30' },
  { id: 'prototype', label: 'Prototype', color: 'bg-purple-500/10 text-purple-500 border-purple-500/30' },
  { id: 'mvp', label: 'MVP', color: 'bg-indigo-500/10 text-indigo-500 border-indigo-500/30' },
  { id: 'early-stage', label: 'Early Stage', color: 'bg-cyan-500/10 text-cyan-500 border-cyan-500/30' },
  { id: 'growth', label: 'Growth Stage', color: 'bg-green-500/10 text-green-500 border-green-500/30' },
  { id: 'scale', label: 'Scale-up', color: 'bg-emerald-500/10 text-emerald-500 border-emerald-500/30' },
  { id: 'established', label: 'Established', color: 'bg-yellow-500/10 text-yellow-500 border-yellow-500/30' },
  { id: 'exited', label: 'Exited / Acquired', color: 'bg-orange-500/10 text-orange-500 border-orange-500/30' },
]

export const FUNDING_STAGES = [
  { id: 'bootstrapped', label: 'Bootstrapped' },
  { id: 'pre-seed', label: 'Pre-Seed' },
  { id: 'seed', label: 'Seed' },
  { id: 'series-a', label: 'Series A' },
  { id: 'series-b', label: 'Series B' },
  { id: 'series-c', label: 'Series C' },
  { id: 'series-d', label: 'Series D+' },
  { id: 'ipo', label: 'IPO / Public' },
  { id: 'acquired', label: 'Acquired' },
  { id: 'grant', label: 'Grant Funded' },
  { id: 'revenue', label: 'Revenue Funded' },
  { id: 'not-applicable', label: 'Not Applicable' },
]

export const REGISTRATION_TYPES = [
  { id: 'pvt-ltd', label: 'Private Limited' },
  { id: 'llp', label: 'LLP' },
  { id: 'opc', label: 'One Person Company' },
  { id: 'partnership', label: 'Partnership Firm' },
  { id: 'sole-proprietorship', label: 'Sole Proprietorship' },
  { id: 'public-ltd', label: 'Public Limited' },
  { id: 'section-8', label: 'Section 8 (Non-Profit)' },
  { id: 'trust', label: 'Trust' },
  { id: 'society', label: 'Society' },
  { id: 'cooperative', label: 'Cooperative' },
  { id: 'not-registered', label: 'Not Yet Registered' },
  { id: 'foreign', label: 'Foreign Entity' },
  { id: 'other', label: 'Other' },
]

export const BUSINESS_MODELS = [
  { id: 'saas', label: 'SaaS (Software as a Service)' },
  { id: 'marketplace', label: 'Marketplace' },
  { id: 'e-commerce', label: 'E-Commerce' },
  { id: 'd2c', label: 'Direct to Consumer (D2C)' },
  { id: 'b2b', label: 'B2B (Business to Business)' },
  { id: 'b2c', label: 'B2C (Business to Consumer)' },
  { id: 'b2b2c', label: 'B2B2C' },
  { id: 'subscription', label: 'Subscription' },
  { id: 'freemium', label: 'Freemium' },
  { id: 'commission', label: 'Commission-based' },
  { id: 'advertising', label: 'Advertising' },
  { id: 'licensing', label: 'Licensing' },
  { id: 'franchise', label: 'Franchise' },
  { id: 'consulting', label: 'Consulting / Services' },
  { id: 'agency', label: 'Agency Model' },
  { id: 'manufacturing', label: 'Manufacturing / Production' },
  { id: 'retail', label: 'Retail' },
  { id: 'wholesale', label: 'Wholesale / Distribution' },
  { id: 'platform', label: 'Platform' },
  { id: 'api', label: 'API / Infrastructure' },
  { id: 'data', label: 'Data Monetization' },
  { id: 'hardware', label: 'Hardware Sales' },
  { id: 'pay-per-use', label: 'Pay-per-Use' },
  { id: 'rental', label: 'Rental / Leasing' },
  { id: 'peer-to-peer', label: 'Peer-to-Peer' },
  { id: 'non-profit', label: 'Non-Profit / Donation' },
  { id: 'crowdfunding', label: 'Crowdfunding' },
  { id: 'affiliate', label: 'Affiliate' },
  { id: 'hybrid', label: 'Hybrid Model' },
  { id: 'other', label: 'Other' },
]

export const METRIC_PRESETS = [
  { id: 'mrr', name: 'Monthly Recurring Revenue', type: 'currency', unit: '$', color: 'green' },
  { id: 'arr', name: 'Annual Recurring Revenue', type: 'currency', unit: '$', color: 'green' },
  { id: 'revenue', name: 'Monthly Revenue', type: 'currency', unit: '$', color: 'green' },
  { id: 'active-users', name: 'Active Users', type: 'number', unit: 'users', color: 'blue' },
  { id: 'total-users', name: 'Total Users', type: 'number', unit: 'users', color: 'blue' },
  { id: 'dau', name: 'Daily Active Users', type: 'number', unit: 'users', color: 'blue' },
  { id: 'mau', name: 'Monthly Active Users', type: 'number', unit: 'users', color: 'blue' },
  { id: 'customers', name: 'Paying Customers', type: 'number', unit: 'customers', color: 'purple' },
  { id: 'retention', name: 'Customer Retention', type: 'percentage', unit: '%', color: 'cyan' },
  { id: 'churn', name: 'Churn Rate', type: 'percentage', unit: '%', color: 'red' },
  { id: 'cac', name: 'Customer Acquisition Cost', type: 'currency', unit: '$', color: 'orange' },
  { id: 'ltv', name: 'Customer Lifetime Value', type: 'currency', unit: '$', color: 'green' },
  { id: 'burn-rate', name: 'Monthly Burn Rate', type: 'currency', unit: '$', color: 'red' },
  { id: 'runway', name: 'Runway (Months)', type: 'number', unit: 'months', color: 'yellow' },
  { id: 'gmv', name: 'Gross Merchandise Value', type: 'currency', unit: '$', color: 'green' },
  { id: 'aov', name: 'Average Order Value', type: 'currency', unit: '$', color: 'green' },
  { id: 'orders', name: 'Total Orders', type: 'number', unit: 'orders', color: 'blue' },
  { id: 'nps', name: 'Net Promoter Score', type: 'number', unit: 'NPS', color: 'purple' },
  { id: 'conversion', name: 'Conversion Rate', type: 'percentage', unit: '%', color: 'green' },
  { id: 'traffic', name: 'Website Traffic', type: 'number', unit: 'visits', color: 'blue' },
  { id: 'downloads', name: 'App Downloads', type: 'number', unit: 'downloads', color: 'blue' },
  { id: 'engagement', name: 'Engagement Rate', type: 'percentage', unit: '%', color: 'purple' },
  { id: 'gross-margin', name: 'Gross Margin', type: 'percentage', unit: '%', color: 'green' },
  { id: 'ebitda', name: 'EBITDA', type: 'currency', unit: '$', color: 'green' },
  { id: 'employees', name: 'Team Size', type: 'number', unit: 'people', color: 'blue' },
  { id: 'custom', name: 'Custom Metric', type: 'number', unit: '', color: 'gray' },
]