// ═══════════════════════════════════════════════════════════════
// VENTURE DOMAIN TAXONOMY — 550+ domains
// Business-oriented, covers every major industry + sub-sectors
// ═══════════════════════════════════════════════════════════════

export interface DomainDef {
  name: string
  slug: string
  category: string
  aliases?: string[]
  popular?: boolean
}

export const VENTURE_DOMAINS: DomainDef[] = [

  // ─── AI / MACHINE LEARNING (30+) ───
  { name: 'AI / Machine Learning', slug: 'ai-ml', category: 'AI & Data', popular: true },
  { name: 'Generative AI', slug: 'gen-ai', category: 'AI & Data', popular: true },
  { name: 'LLM Applications', slug: 'llm-apps', category: 'AI & Data', popular: true },
  { name: 'AI Agents', slug: 'ai-agents', category: 'AI & Data', popular: true },
  { name: 'AI Copilots', slug: 'ai-copilots', category: 'AI & Data' },
  { name: 'Computer Vision', slug: 'computer-vision', category: 'AI & Data' },
  { name: 'Natural Language Processing', slug: 'nlp', category: 'AI & Data' },
  { name: 'Speech AI', slug: 'speech-ai', category: 'AI & Data' },
  { name: 'Voice AI', slug: 'voice-ai', category: 'AI & Data' },
  { name: 'Conversational AI', slug: 'conversational-ai', category: 'AI & Data' },
  { name: 'AI Infrastructure', slug: 'ai-infra', category: 'AI & Data' },
  { name: 'MLOps Platforms', slug: 'mlops', category: 'AI & Data' },
  { name: 'Model Training Platforms', slug: 'model-training', category: 'AI & Data' },
  { name: 'AutoML', slug: 'automl', category: 'AI & Data' },
  { name: 'AI Safety', slug: 'ai-safety', category: 'AI & Data' },
  { name: 'AI Alignment', slug: 'ai-alignment', category: 'AI & Data' },
  { name: 'Recommendation Systems', slug: 'recsys', category: 'AI & Data' },
  { name: 'Predictive Analytics', slug: 'predictive-analytics', category: 'AI & Data' },
  { name: 'Synthetic Data', slug: 'synthetic-data', category: 'AI & Data' },
  { name: 'Foundation Models', slug: 'foundation-models', category: 'AI & Data' },
  { name: 'Multimodal AI', slug: 'multimodal-ai', category: 'AI & Data' },
  { name: 'Reinforcement Learning', slug: 'rl', category: 'AI & Data' },
  { name: 'Vector Databases', slug: 'vector-db', category: 'AI & Data' },
  { name: 'RAG Platforms', slug: 'rag', category: 'AI & Data' },
  { name: 'AI Video Generation', slug: 'ai-video', category: 'AI & Data' },
  { name: 'AI Image Generation', slug: 'ai-image', category: 'AI & Data' },
  { name: 'AI Music Generation', slug: 'ai-music', category: 'AI & Data' },
  { name: 'AI Voice Cloning', slug: 'voice-cloning', category: 'AI & Data' },
  { name: 'AI Content Moderation', slug: 'ai-moderation', category: 'AI & Data' },
  { name: 'AI Search', slug: 'ai-search', category: 'AI & Data' },
  { name: 'Robotic Process Automation', slug: 'rpa', category: 'AI & Data' },

  // ─── DATA & ANALYTICS (20+) ───
  { name: 'Data Engineering', slug: 'data-engineering', category: 'AI & Data' },
  { name: 'Data Analytics', slug: 'data-analytics', category: 'AI & Data' },
  { name: 'Business Intelligence', slug: 'bi', category: 'AI & Data', aliases: ['BI'] },
  { name: 'Data Warehousing', slug: 'data-warehousing', category: 'AI & Data' },
  { name: 'Data Lakes', slug: 'data-lakes', category: 'AI & Data' },
  { name: 'Data Governance', slug: 'data-governance', category: 'AI & Data' },
  { name: 'Data Catalogs', slug: 'data-catalogs', category: 'AI & Data' },
  { name: 'Data Extraction/ETL', slug: 'etl', category: 'AI & Data' },
  { name: 'Reverse ETL', slug: 'reverse-etl', category: 'AI & Data' },
  { name: 'Data Mining & Management', slug: 'data-mining', category: 'AI & Data' },
  { name: 'Real-time Analytics', slug: 'realtime-analytics', category: 'AI & Data' },
  { name: 'Customer Data Platform', slug: 'cdp', category: 'AI & Data' },
  { name: 'Product Analytics', slug: 'product-analytics', category: 'AI & Data' },
  { name: 'Marketing Analytics', slug: 'marketing-analytics', category: 'AI & Data' },
  { name: 'Session Replay', slug: 'session-replay', category: 'AI & Data' },
  { name: 'Data Observability', slug: 'data-observability', category: 'AI & Data' },
  { name: 'Data Quality', slug: 'data-quality', category: 'AI & Data' },
  { name: 'Data Contracts', slug: 'data-contracts', category: 'AI & Data' },
  { name: 'Streaming Data', slug: 'streaming-data', category: 'AI & Data' },
  { name: 'Data Mesh', slug: 'data-mesh', category: 'AI & Data' },

  // ─── FINTECH (45+) ───
  { name: 'FinTech', slug: 'fintech', category: 'FinTech', popular: true },
  { name: 'Digital Banking', slug: 'digital-banking', category: 'FinTech' },
  { name: 'Neobanks', slug: 'neobanks', category: 'FinTech' },
  { name: 'Payments', slug: 'payments', category: 'FinTech', popular: true },
  { name: 'Payment Processors', slug: 'payment-processors', category: 'FinTech' },
  { name: 'Payment Gateways', slug: 'payment-gateways', category: 'FinTech' },
  { name: 'Lending', slug: 'lending', category: 'FinTech' },
  { name: 'P2P Lending', slug: 'p2p-lending', category: 'FinTech' },
  { name: 'SMB Lending', slug: 'smb-lending', category: 'FinTech' },
  { name: 'Buy Now Pay Later', slug: 'bnpl', category: 'FinTech' },
  { name: 'InsurTech', slug: 'insurtech', category: 'FinTech' },
  { name: 'Health Insurance Tech', slug: 'health-insurance', category: 'FinTech' },
  { name: 'Life Insurance Tech', slug: 'life-insurance', category: 'FinTech' },
  { name: 'WealthTech', slug: 'wealthtech', category: 'FinTech' },
  { name: 'RegTech', slug: 'regtech', category: 'FinTech' },
  { name: 'Compliance Tech', slug: 'compliance-tech', category: 'FinTech' },
  { name: 'Robo-Advisors', slug: 'robo-advisors', category: 'FinTech' },
  { name: 'Trading Platforms', slug: 'trading-platforms', category: 'FinTech' },
  { name: 'Options Trading', slug: 'options-trading', category: 'FinTech' },
  { name: 'Crypto Exchanges', slug: 'crypto-exchanges', category: 'FinTech' },
  { name: 'Cryptocurrency', slug: 'crypto', category: 'FinTech' },
  { name: 'DeFi', slug: 'defi', category: 'FinTech', popular: true },
  { name: 'Web3', slug: 'web3', category: 'FinTech' },
  { name: 'Blockchain', slug: 'blockchain', category: 'FinTech' },
  { name: 'NFT / Digital Assets', slug: 'nft', category: 'FinTech' },
  { name: 'Stablecoins', slug: 'stablecoins', category: 'FinTech' },
  { name: 'CBDC', slug: 'cbdc', category: 'FinTech' },
  { name: 'Financial Data', slug: 'financial-data', category: 'FinTech' },
  { name: 'Embedded Finance', slug: 'embedded-finance', category: 'FinTech' },
  { name: 'Banking-as-a-Service', slug: 'baas', category: 'FinTech' },
  { name: 'Remittances', slug: 'remittances', category: 'FinTech' },
  { name: 'Personal Finance', slug: 'personal-finance', category: 'FinTech' },
  { name: 'Savings Apps', slug: 'savings-apps', category: 'FinTech' },
  { name: 'Corporate Cards', slug: 'corporate-cards', category: 'FinTech' },
  { name: 'Expense Management', slug: 'expense-mgmt', category: 'FinTech' },
  { name: 'Accounting Software', slug: 'accounting-sw', category: 'FinTech' },
  { name: 'Tax Software', slug: 'tax-sw', category: 'FinTech' },
  { name: 'Anti-Fraud', slug: 'anti-fraud', category: 'FinTech' },
  { name: 'KYC / AML', slug: 'kyc-aml', category: 'FinTech' },
  { name: 'Identity Verification', slug: 'identity-verification', category: 'FinTech' },
  { name: 'Cross-border Payments', slug: 'cross-border-payments', category: 'FinTech' },
  { name: 'Real Estate Investment', slug: 're-investment', category: 'FinTech' },
  { name: 'Fractional Investing', slug: 'fractional-investing', category: 'FinTech' },
  { name: 'Alternative Assets', slug: 'alternative-assets', category: 'FinTech' },
  { name: 'Wealth Management', slug: 'wealth-mgmt', category: 'FinTech' },
  { name: 'Financial Planning', slug: 'financial-planning', category: 'FinTech' },

  // ─── HEALTHTECH / BIOTECH (40+) ───
  { name: 'HealthTech', slug: 'healthtech', category: 'Health & Bio', popular: true },
  { name: 'MedTech', slug: 'medtech', category: 'Health & Bio' },
  { name: 'Digital Health', slug: 'digital-health', category: 'Health & Bio' },
  { name: 'Telemedicine', slug: 'telemedicine', category: 'Health & Bio' },
  { name: 'Telehealth', slug: 'telehealth', category: 'Health & Bio' },
  { name: 'Remote Patient Monitoring', slug: 'rpm', category: 'Health & Bio' },
  { name: 'Mental Health', slug: 'mental-health', category: 'Health & Bio', popular: true },
  { name: 'Meditation Apps', slug: 'meditation', category: 'Health & Bio' },
  { name: 'Therapy Platforms', slug: 'therapy-platforms', category: 'Health & Bio' },
  { name: 'Fitness & Wellness', slug: 'fitness', category: 'Health & Bio' },
  { name: 'Connected Fitness', slug: 'connected-fitness', category: 'Health & Bio' },
  { name: 'Wearables', slug: 'wearables', category: 'Health & Bio' },
  { name: 'Health Records / EHR', slug: 'ehr', category: 'Health & Bio' },
  { name: 'Clinical Trials', slug: 'clinical-trials', category: 'Health & Bio' },
  { name: 'Pharmaceuticals', slug: 'pharma', category: 'Health & Bio' },
  { name: 'Drug Discovery', slug: 'drug-discovery', category: 'Health & Bio' },
  { name: 'AI Drug Discovery', slug: 'ai-drug-discovery', category: 'Health & Bio' },
  { name: 'BioTech', slug: 'biotech', category: 'Health & Bio', popular: true },
  { name: 'Genomics', slug: 'genomics', category: 'Health & Bio' },
  { name: 'Precision Medicine', slug: 'precision-medicine', category: 'Health & Bio' },
  { name: 'Personalized Medicine', slug: 'personalized-medicine', category: 'Health & Bio' },
  { name: 'Medical Devices', slug: 'medical-devices', category: 'Health & Bio' },
  { name: 'Diagnostics', slug: 'diagnostics', category: 'Health & Bio' },
  { name: 'AI Diagnostics', slug: 'ai-diagnostics', category: 'Health & Bio' },
  { name: 'Radiology AI', slug: 'radiology-ai', category: 'Health & Bio' },
  { name: 'Pathology AI', slug: 'pathology-ai', category: 'Health & Bio' },
  { name: 'Elder Care', slug: 'elder-care', category: 'Health & Bio' },
  { name: 'Pediatric Health', slug: 'pediatric-health', category: 'Health & Bio' },
  { name: "Women's Health / FemTech", slug: 'femtech', category: 'Health & Bio' },
  { name: 'Reproductive Health', slug: 'reproductive-health', category: 'Health & Bio' },
  { name: 'Fertility Tech', slug: 'fertility', category: 'Health & Bio' },
  { name: 'Sexual Health', slug: 'sexual-health', category: 'Health & Bio' },
  { name: 'Nutrition', slug: 'nutrition', category: 'Health & Bio' },
  { name: 'Sleep Tech', slug: 'sleep-tech', category: 'Health & Bio' },
  { name: 'Longevity', slug: 'longevity', category: 'Health & Bio' },
  { name: 'Anti-Aging', slug: 'anti-aging', category: 'Health & Bio' },
  { name: 'Synthetic Biology', slug: 'synbio', category: 'Health & Bio' },
  { name: 'Cell Therapy', slug: 'cell-therapy', category: 'Health & Bio' },
  { name: 'Gene Therapy', slug: 'gene-therapy', category: 'Health & Bio' },
  { name: 'mRNA Technology', slug: 'mrna', category: 'Health & Bio' },
  { name: 'Bioinformatics', slug: 'bioinformatics', category: 'Health & Bio' },
  { name: 'Lab Automation', slug: 'lab-automation', category: 'Health & Bio' },
  { name: 'Hospital Operations', slug: 'hospital-ops', category: 'Health & Bio' },
  { name: 'Healthcare Payments', slug: 'healthcare-payments', category: 'Health & Bio' },

  // ─── CLIMATE / CLEAN TECH (35+) ───
  { name: 'ClimateTech', slug: 'climatetech', category: 'Climate & Energy', popular: true },
  { name: 'CleanTech', slug: 'cleantech', category: 'Climate & Energy' },
  { name: 'Renewable Energy', slug: 'renewable-energy', category: 'Climate & Energy' },
  { name: 'Solar Energy', slug: 'solar', category: 'Climate & Energy' },
  { name: 'Solar Financing', slug: 'solar-financing', category: 'Climate & Energy' },
  { name: 'Wind Energy', slug: 'wind', category: 'Climate & Energy' },
  { name: 'Offshore Wind', slug: 'offshore-wind', category: 'Climate & Energy' },
  { name: 'Hydrogen', slug: 'hydrogen', category: 'Climate & Energy' },
  { name: 'Green Hydrogen', slug: 'green-hydrogen', category: 'Climate & Energy' },
  { name: 'Battery Tech', slug: 'battery-tech', category: 'Climate & Energy' },
  { name: 'Solid-State Batteries', slug: 'solid-state-batteries', category: 'Climate & Energy' },
  { name: 'Energy Storage', slug: 'energy-storage', category: 'Climate & Energy' },
  { name: 'Grid Storage', slug: 'grid-storage', category: 'Climate & Energy' },
  { name: 'Smart Grid', slug: 'smart-grid', category: 'Climate & Energy' },
  { name: 'Virtual Power Plants', slug: 'vpp', category: 'Climate & Energy' },
  { name: 'Carbon Capture', slug: 'carbon-capture', category: 'Climate & Energy' },
  { name: 'Direct Air Capture', slug: 'dac', category: 'Climate & Energy' },
  { name: 'Carbon Markets', slug: 'carbon-markets', category: 'Climate & Energy' },
  { name: 'Carbon Accounting', slug: 'carbon-accounting', category: 'Climate & Energy' },
  { name: 'Sustainability', slug: 'sustainability', category: 'Climate & Energy' },
  { name: 'ESG', slug: 'esg', category: 'Climate & Energy' },
  { name: 'Circular Economy', slug: 'circular-economy', category: 'Climate & Energy' },
  { name: 'Waste Management', slug: 'waste-mgmt', category: 'Climate & Energy' },
  { name: 'Recycling Tech', slug: 'recycling', category: 'Climate & Energy' },
  { name: 'Water Tech', slug: 'water-tech', category: 'Climate & Energy' },
  { name: 'Water Treatment', slug: 'water-treatment', category: 'Climate & Energy' },
  { name: 'Green Building', slug: 'green-building', category: 'Climate & Energy' },
  { name: 'Building Efficiency', slug: 'building-efficiency', category: 'Climate & Energy' },
  { name: 'Electric Vehicles', slug: 'ev', category: 'Climate & Energy', popular: true },
  { name: 'EV Charging', slug: 'ev-charging', category: 'Climate & Energy' },
  { name: 'EV Batteries', slug: 'ev-batteries', category: 'Climate & Energy' },
  { name: 'Nuclear', slug: 'nuclear', category: 'Climate & Energy' },
  { name: 'SMR / Small Reactors', slug: 'smr', category: 'Climate & Energy' },
  { name: 'Fusion Energy', slug: 'fusion', category: 'Climate & Energy' },
  { name: 'Geothermal', slug: 'geothermal', category: 'Climate & Energy' },
  { name: 'Wave Energy', slug: 'wave-energy', category: 'Climate & Energy' },

  // ─── AGRITECH / FOODTECH (25+) ───
  { name: 'AgriTech', slug: 'agritech', category: 'AgriTech & Food', popular: true },
  { name: 'FoodTech', slug: 'foodtech', category: 'AgriTech & Food' },
  { name: 'Precision Agriculture', slug: 'precision-ag', category: 'AgriTech & Food' },
  { name: 'Vertical Farming', slug: 'vertical-farming', category: 'AgriTech & Food' },
  { name: 'Indoor Farming', slug: 'indoor-farming', category: 'AgriTech & Food' },
  { name: 'Alternative Protein', slug: 'alt-protein', category: 'AgriTech & Food' },
  { name: 'Plant-based Foods', slug: 'plant-based', category: 'AgriTech & Food' },
  { name: 'Cellular Agriculture', slug: 'cellular-ag', category: 'AgriTech & Food' },
  { name: 'Cultivated Meat', slug: 'cultivated-meat', category: 'AgriTech & Food' },
  { name: 'Farm Robotics', slug: 'farm-robotics', category: 'AgriTech & Food' },
  { name: 'Ag Drones', slug: 'ag-drones', category: 'AgriTech & Food' },
  { name: 'Livestock Tech', slug: 'livestock-tech', category: 'AgriTech & Food' },
  { name: 'Aquaculture', slug: 'aquaculture', category: 'AgriTech & Food' },
  { name: 'Crop Health Monitoring', slug: 'crop-monitoring', category: 'AgriTech & Food' },
  { name: 'Soil Health', slug: 'soil-health', category: 'AgriTech & Food' },
  { name: 'Farm Management Software', slug: 'farm-mgmt-sw', category: 'AgriTech & Food' },
  { name: 'AgFinance', slug: 'agfinance', category: 'AgriTech & Food' },
  { name: 'Restaurant Tech', slug: 'restaurant-tech', category: 'AgriTech & Food' },
  { name: 'Ghost Kitchens', slug: 'ghost-kitchens', category: 'AgriTech & Food' },
  { name: 'Food Delivery', slug: 'food-delivery', category: 'AgriTech & Food' },
  { name: 'Grocery Delivery', slug: 'grocery-delivery', category: 'AgriTech & Food' },
  { name: 'Meal Kits', slug: 'meal-kits', category: 'AgriTech & Food' },
  { name: 'Food Safety', slug: 'food-safety', category: 'AgriTech & Food' },
  { name: 'Sustainable Agriculture', slug: 'sustainable-ag', category: 'AgriTech & Food' },
  { name: 'Food Traceability', slug: 'food-traceability', category: 'AgriTech & Food' },

  // ─── EDTECH (25+) ───
  { name: 'EdTech', slug: 'edtech', category: 'Education', popular: true },
  { name: 'K-12 Education', slug: 'k12', category: 'Education' },
  { name: 'Higher Education', slug: 'higher-ed', category: 'Education' },
  { name: 'Online Courses / MOOCs', slug: 'moocs', category: 'Education' },
  { name: 'Corporate Learning', slug: 'corp-learning', category: 'Education' },
  { name: 'Language Learning', slug: 'language-learning', category: 'Education' },
  { name: 'Coding Bootcamps', slug: 'coding-bootcamps', category: 'Education' },
  { name: 'Skills Training', slug: 'skills-training', category: 'Education' },
  { name: 'Test Prep', slug: 'test-prep', category: 'Education' },
  { name: 'Tutoring', slug: 'tutoring', category: 'Education' },
  { name: 'Learning Management', slug: 'lms', category: 'Education' },
  { name: 'Student Loans', slug: 'student-loans', category: 'Education' },
  { name: 'AI Tutors', slug: 'ai-tutors', category: 'Education' },
  { name: 'STEM Education', slug: 'stem-ed', category: 'Education' },
  { name: 'Early Childhood', slug: 'early-childhood', category: 'Education' },
  { name: 'Special Education', slug: 'special-ed', category: 'Education' },
  { name: 'Continuing Education', slug: 'continuing-ed', category: 'Education' },
  { name: 'Certification Platforms', slug: 'certifications', category: 'Education' },
  { name: 'Micro-credentials', slug: 'micro-credentials', category: 'Education' },
  { name: 'Vocational Training', slug: 'vocational', category: 'Education' },
  { name: 'Reskilling Platforms', slug: 'reskilling', category: 'Education' },
  { name: 'School Management', slug: 'school-mgmt', category: 'Education' },
  { name: 'EdTech Analytics', slug: 'edtech-analytics', category: 'Education' },
  { name: 'Adaptive Learning', slug: 'adaptive-learning', category: 'Education' },
  { name: 'Educational Games', slug: 'edu-games', category: 'Education' },

  // ─── E-COMMERCE / RETAIL (30+) ───
  { name: 'E-Commerce', slug: 'ecommerce', category: 'E-Commerce & Retail', popular: true },
  { name: 'D2C Brands', slug: 'd2c', category: 'E-Commerce & Retail' },
  { name: 'Retail Tech', slug: 'retail-tech', category: 'E-Commerce & Retail' },
  { name: 'Marketplaces', slug: 'marketplaces', category: 'E-Commerce & Retail', popular: true },
  { name: 'B2B Marketplace', slug: 'b2b-marketplace', category: 'E-Commerce & Retail' },
  { name: 'Wholesale', slug: 'wholesale', category: 'E-Commerce & Retail' },
  { name: 'Social Commerce', slug: 'social-commerce', category: 'E-Commerce & Retail' },
  { name: 'Live Commerce', slug: 'live-commerce', category: 'E-Commerce & Retail' },
  { name: 'Recommerce / Resale', slug: 'recommerce', category: 'E-Commerce & Retail' },
  { name: 'Rental / Sharing', slug: 'rental', category: 'E-Commerce & Retail' },
  { name: 'Subscription Commerce', slug: 'subscription-commerce', category: 'E-Commerce & Retail' },
  { name: 'Fashion', slug: 'fashion', category: 'E-Commerce & Retail' },
  { name: 'Sustainable Fashion', slug: 'sustainable-fashion', category: 'E-Commerce & Retail' },
  { name: 'Beauty', slug: 'beauty', category: 'E-Commerce & Retail' },
  { name: 'Personal Care', slug: 'personal-care', category: 'E-Commerce & Retail' },
  { name: 'Jewelry', slug: 'jewelry', category: 'E-Commerce & Retail' },
  { name: 'Home Goods', slug: 'home-goods', category: 'E-Commerce & Retail' },
  { name: 'Furniture', slug: 'furniture', category: 'E-Commerce & Retail' },
  { name: 'Consumer Electronics', slug: 'consumer-electronics', category: 'E-Commerce & Retail' },
  { name: 'Point of Sale', slug: 'pos', category: 'E-Commerce & Retail' },
  { name: 'Inventory Management', slug: 'inventory-mgmt', category: 'E-Commerce & Retail' },
  { name: 'Order Management', slug: 'order-mgmt', category: 'E-Commerce & Retail' },
  { name: 'Warehouse Management', slug: 'wms', category: 'E-Commerce & Retail' },
  { name: 'Last-Mile Delivery', slug: 'last-mile', category: 'E-Commerce & Retail' },
  { name: 'Q-Commerce', slug: 'q-commerce', category: 'E-Commerce & Retail' },
  { name: 'Returns Management', slug: 'returns', category: 'E-Commerce & Retail' },
  { name: 'Product Photography', slug: 'product-photography', category: 'E-Commerce & Retail' },
  { name: 'Product Reviews', slug: 'product-reviews', category: 'E-Commerce & Retail' },
  { name: 'Loyalty Programs', slug: 'loyalty', category: 'E-Commerce & Retail' },
  { name: 'Personalization Engines', slug: 'personalization-engines', category: 'E-Commerce & Retail' },

  // ─── SAAS / ENTERPRISE (40+) ───
  { name: 'SaaS', slug: 'saas', category: 'SaaS & Enterprise', popular: true },
  { name: 'B2B SaaS', slug: 'b2b-saas', category: 'SaaS & Enterprise', popular: true },
  { name: 'Enterprise Software', slug: 'enterprise-sw', category: 'SaaS & Enterprise' },
  { name: 'CRM', slug: 'crm', category: 'SaaS & Enterprise' },
  { name: 'ERP', slug: 'erp', category: 'SaaS & Enterprise' },
  { name: 'HR Tech', slug: 'hr-tech', category: 'SaaS & Enterprise' },
  { name: 'Payroll', slug: 'payroll', category: 'SaaS & Enterprise' },
  { name: 'Recruiting Tech', slug: 'recruiting', category: 'SaaS & Enterprise' },
  { name: 'People Analytics', slug: 'people-analytics', category: 'SaaS & Enterprise' },
  { name: 'Employee Engagement', slug: 'employee-engagement', category: 'SaaS & Enterprise' },
  { name: 'Legal Tech', slug: 'legaltech', category: 'SaaS & Enterprise' },
  { name: 'Contract Management', slug: 'contract-mgmt', category: 'SaaS & Enterprise' },
  { name: 'E-Signature', slug: 'e-signature', category: 'SaaS & Enterprise' },
  { name: 'Sales Tech', slug: 'sales-tech', category: 'SaaS & Enterprise' },
  { name: 'Sales Enablement', slug: 'sales-enablement', category: 'SaaS & Enterprise' },
  { name: 'Sales Intelligence', slug: 'sales-intelligence', category: 'SaaS & Enterprise' },
  { name: 'Marketing Tech', slug: 'martech', category: 'SaaS & Enterprise' },
  { name: 'Email Marketing', slug: 'email-marketing', category: 'SaaS & Enterprise' },
  { name: 'SMS Marketing', slug: 'sms-marketing', category: 'SaaS & Enterprise' },
  { name: 'AdTech', slug: 'adtech', category: 'SaaS & Enterprise' },
  { name: 'Customer Success', slug: 'cs-sw', category: 'SaaS & Enterprise' },
  { name: 'Customer Support', slug: 'customer-support', category: 'SaaS & Enterprise' },
  { name: 'Help Desk', slug: 'help-desk', category: 'SaaS & Enterprise' },
  { name: 'AI Customer Service', slug: 'ai-customer-service', category: 'SaaS & Enterprise' },
  { name: 'Project Management', slug: 'project-mgmt', category: 'SaaS & Enterprise' },
  { name: 'Task Management', slug: 'task-mgmt', category: 'SaaS & Enterprise' },
  { name: 'Collaboration Tools', slug: 'collaboration', category: 'SaaS & Enterprise' },
  { name: 'Communication', slug: 'communication', category: 'SaaS & Enterprise' },
  { name: 'Video Conferencing', slug: 'video-conferencing', category: 'SaaS & Enterprise' },
  { name: 'Async Video', slug: 'async-video', category: 'SaaS & Enterprise' },
  { name: 'Knowledge Management', slug: 'knowledge-mgmt', category: 'SaaS & Enterprise' },
  { name: 'Wiki / Docs', slug: 'wiki', category: 'SaaS & Enterprise' },
  { name: 'Workflow Automation', slug: 'workflow-automation', category: 'SaaS & Enterprise' },
  { name: 'No-Code / Low-Code', slug: 'no-code', category: 'SaaS & Enterprise', popular: true },
  { name: 'Business Process Automation', slug: 'bpa', category: 'SaaS & Enterprise' },
  { name: 'Vertical SaaS', slug: 'vertical-saas', category: 'SaaS & Enterprise' },
  { name: 'Field Service Management', slug: 'fsm', category: 'SaaS & Enterprise' },
  { name: 'Procurement Software', slug: 'procurement', category: 'SaaS & Enterprise' },
  { name: 'Vendor Management', slug: 'vendor-mgmt', category: 'SaaS & Enterprise' },
  { name: 'Contract Lifecycle Management', slug: 'clm', category: 'SaaS & Enterprise' },

  // ─── DEVELOPER TOOLS (30+) ───
  { name: 'Developer Tools', slug: 'devtools', category: 'Developer Tools', popular: true },
  { name: 'DevOps', slug: 'devops', category: 'Developer Tools' },
  { name: 'CI/CD', slug: 'ci-cd', category: 'Developer Tools' },
  { name: 'Observability', slug: 'observability', category: 'Developer Tools' },
  { name: 'Monitoring & Logging', slug: 'monitoring', category: 'Developer Tools' },
  { name: 'APM', slug: 'apm', category: 'Developer Tools' },
  { name: 'Error Tracking', slug: 'error-tracking', category: 'Developer Tools' },
  { name: 'Code Review', slug: 'code-review', category: 'Developer Tools' },
  { name: 'Testing Tools', slug: 'testing', category: 'Developer Tools' },
  { name: 'API Development', slug: 'api-dev', category: 'Developer Tools' },
  { name: 'API Gateway', slug: 'api-gateway', category: 'Developer Tools' },
  { name: 'API Management', slug: 'api-management', category: 'Developer Tools' },
  { name: 'Serverless', slug: 'serverless', category: 'Developer Tools' },
  { name: 'Edge Computing', slug: 'edge-computing', category: 'Developer Tools' },
  { name: 'Container Orchestration', slug: 'containers', category: 'Developer Tools' },
  { name: 'Kubernetes Platforms', slug: 'kubernetes-platforms', category: 'Developer Tools' },
  { name: 'Databases', slug: 'databases', category: 'Developer Tools' },
  { name: 'PostgreSQL Extensions', slug: 'postgres-ext', category: 'Developer Tools' },
  { name: 'Time-series DB', slug: 'timeseries-db', category: 'Developer Tools' },
  { name: 'Graph Databases', slug: 'graph-db', category: 'Developer Tools' },
  { name: 'Search Infrastructure', slug: 'search-infra', category: 'Developer Tools' },
  { name: 'Analytics Engines', slug: 'analytics-engines', category: 'Developer Tools' },
  { name: 'Data Streaming', slug: 'data-streaming', category: 'Developer Tools' },
  { name: 'Message Queues', slug: 'message-queues', category: 'Developer Tools' },
  { name: 'Feature Flags', slug: 'feature-flags', category: 'Developer Tools' },
  { name: 'A/B Testing', slug: 'ab-testing', category: 'Developer Tools' },
  { name: 'Developer Productivity', slug: 'dev-productivity', category: 'Developer Tools' },
  { name: 'AI Coding Assistants', slug: 'ai-coding', category: 'Developer Tools', popular: true },
  { name: 'Open Source Startups', slug: 'oss-startups', category: 'Developer Tools' },
  { name: 'Cloud Infrastructure', slug: 'cloud-infra', category: 'Developer Tools' },
  { name: 'Backend-as-a-Service', slug: 'backend-as-service', category: 'Developer Tools' },
  { name: 'Auth-as-a-Service', slug: 'auth-as-service', category: 'Developer Tools' },
  { name: 'Notifications-as-a-Service', slug: 'notifications-as-service', category: 'Developer Tools' },

  // ─── CYBERSECURITY (25+) ───
  { name: 'Cybersecurity', slug: 'cybersecurity', category: 'Security' },
  { name: 'Application Security', slug: 'appsec', category: 'Security' },
  { name: 'Cloud Security', slug: 'cloud-security', category: 'Security' },
  { name: 'Container Security', slug: 'container-security', category: 'Security' },
  { name: 'Endpoint Security', slug: 'endpoint-security', category: 'Security' },
  { name: 'Identity & Access', slug: 'iam', category: 'Security' },
  { name: 'Zero Trust', slug: 'zero-trust', category: 'Security' },
  { name: 'SIEM', slug: 'siem', category: 'Security' },
  { name: 'SOAR', slug: 'soar', category: 'Security' },
  { name: 'XDR', slug: 'xdr', category: 'Security' },
  { name: 'Threat Intelligence', slug: 'threat-intel', category: 'Security' },
  { name: 'Vulnerability Management', slug: 'vuln-mgmt', category: 'Security' },
  { name: 'Penetration Testing', slug: 'pentest', category: 'Security' },
  { name: 'Password Managers', slug: 'password-mgmt', category: 'Security' },
  { name: 'Encryption', slug: 'encryption', category: 'Security' },
  { name: 'Privacy Tech', slug: 'privacy-tech', category: 'Security' },
  { name: 'Compliance', slug: 'compliance', category: 'Security' },
  { name: 'GDPR Tools', slug: 'gdpr', category: 'Security' },
  { name: 'Data Privacy', slug: 'data-privacy', category: 'Security' },
  { name: 'Fraud Detection', slug: 'fraud-detection', category: 'Security' },
  { name: 'Bot Protection', slug: 'bot-protection', category: 'Security' },
  { name: 'DDoS Protection', slug: 'ddos-protection', category: 'Security' },
  { name: 'Email Security', slug: 'email-security', category: 'Security' },
  { name: 'Phishing Protection', slug: 'phishing-protection', category: 'Security' },
  { name: 'Security Awareness Training', slug: 'security-awareness', category: 'Security' },

  // ─── CONSUMER / SOCIAL (30+) ───
  { name: 'Consumer Apps', slug: 'consumer-apps', category: 'Consumer' },
  { name: 'Social Media', slug: 'social-media', category: 'Consumer' },
  { name: 'Social Networks', slug: 'social-networks', category: 'Consumer' },
  { name: 'Community Platforms', slug: 'community-platforms', category: 'Consumer' },
  { name: 'Dating', slug: 'dating', category: 'Consumer' },
  { name: 'Photo & Video', slug: 'photo-video', category: 'Consumer' },
  { name: 'Photo Editing Apps', slug: 'photo-editing-apps', category: 'Consumer' },
  { name: 'Video Editing Apps', slug: 'video-editing-apps', category: 'Consumer' },
  { name: 'Music', slug: 'music', category: 'Consumer' },
  { name: 'Podcasts', slug: 'podcasts', category: 'Consumer' },
  { name: 'Streaming', slug: 'streaming', category: 'Consumer' },
  { name: 'Reading Apps', slug: 'reading-apps', category: 'Consumer' },
  { name: 'News & Media', slug: 'news-media', category: 'Consumer' },
  { name: 'Publishing', slug: 'publishing', category: 'Consumer' },
  { name: 'Newsletter Platforms', slug: 'newsletters', category: 'Consumer' },
  { name: 'Creator Economy', slug: 'creator-economy', category: 'Consumer', popular: true },
  { name: 'Creator Tools', slug: 'creator-tools', category: 'Consumer' },
  { name: 'Influencer Marketing', slug: 'influencer-marketing', category: 'Consumer' },
  { name: 'Fan Engagement', slug: 'fan-engagement', category: 'Consumer' },
  { name: 'Kids & Parenting', slug: 'kids-parenting', category: 'Consumer' },
  { name: 'Pets', slug: 'pets', category: 'Consumer' },
  { name: 'Home Services', slug: 'home-services', category: 'Consumer' },
  { name: 'On-Demand Services', slug: 'on-demand', category: 'Consumer' },
  { name: 'Personal Care Apps', slug: 'personal-care-apps', category: 'Consumer' },
  { name: 'Productivity Apps', slug: 'productivity-apps', category: 'Consumer' },
  { name: 'Habits & Journaling', slug: 'habits', category: 'Consumer' },
  { name: 'Meditation & Wellness Apps', slug: 'meditation-apps', category: 'Consumer' },
  { name: 'Community-Owned', slug: 'community-owned', category: 'Consumer' },
  { name: 'Marketplace Communities', slug: 'marketplace-communities', category: 'Consumer' },
  { name: 'Fandoms', slug: 'fandoms', category: 'Consumer' },

  // ─── GAMING & ENTERTAINMENT (20+) ───
  { name: 'Gaming', slug: 'gaming', category: 'Gaming & Entertainment' },
  { name: 'Game Development Studios', slug: 'game-studios', category: 'Gaming & Entertainment' },
  { name: 'Mobile Gaming', slug: 'mobile-gaming', category: 'Gaming & Entertainment' },
  { name: 'PC Gaming', slug: 'pc-gaming', category: 'Gaming & Entertainment' },
  { name: 'Console Gaming', slug: 'console-gaming', category: 'Gaming & Entertainment' },
  { name: 'Cloud Gaming', slug: 'cloud-gaming', category: 'Gaming & Entertainment' },
  { name: 'Esports', slug: 'esports', category: 'Gaming & Entertainment' },
  { name: 'Game Streaming', slug: 'game-streaming', category: 'Gaming & Entertainment' },
  { name: 'Web3 Gaming', slug: 'web3-gaming', category: 'Gaming & Entertainment' },
  { name: 'AR / VR', slug: 'ar-vr', category: 'Gaming & Entertainment' },
  { name: 'Metaverse', slug: 'metaverse', category: 'Gaming & Entertainment' },
  { name: 'Spatial Computing', slug: 'spatial-computing', category: 'Gaming & Entertainment' },
  { name: 'Media Production', slug: 'media-production', category: 'Gaming & Entertainment' },
  { name: 'Film & TV', slug: 'film-tv', category: 'Gaming & Entertainment' },
  { name: 'Live Events', slug: 'live-events', category: 'Gaming & Entertainment' },
  { name: 'Ticketing', slug: 'ticketing', category: 'Gaming & Entertainment' },
  { name: 'Music Distribution', slug: 'music-distribution', category: 'Gaming & Entertainment' },
  { name: 'Content Distribution', slug: 'content-distribution', category: 'Gaming & Entertainment' },
  { name: 'DAW / Music Production', slug: 'daw', category: 'Gaming & Entertainment' },
  { name: 'Interactive Entertainment', slug: 'interactive-entertainment', category: 'Gaming & Entertainment' },

  // ─── HARDWARE / DEEP TECH (35+) ───
  { name: 'Hardware', slug: 'hardware', category: 'Hardware & Deep Tech' },
  { name: 'Semiconductors', slug: 'semiconductors', category: 'Hardware & Deep Tech' },
  { name: 'Chip Design', slug: 'chip-design', category: 'Hardware & Deep Tech' },
  { name: 'AI Chips', slug: 'ai-chips', category: 'Hardware & Deep Tech' },
  { name: 'Robotics', slug: 'robotics', category: 'Hardware & Deep Tech', popular: true },
  { name: 'Industrial Robotics', slug: 'industrial-robotics', category: 'Hardware & Deep Tech' },
  { name: 'Warehouse Robotics', slug: 'warehouse-robotics', category: 'Hardware & Deep Tech' },
  { name: 'Humanoid Robots', slug: 'humanoids', category: 'Hardware & Deep Tech' },
  { name: 'Service Robotics', slug: 'service-robotics', category: 'Hardware & Deep Tech' },
  { name: 'Surgical Robotics', slug: 'surgical-robotics', category: 'Hardware & Deep Tech' },
  { name: 'Drones', slug: 'drones', category: 'Hardware & Deep Tech' },
  { name: 'Commercial Drones', slug: 'commercial-drones', category: 'Hardware & Deep Tech' },
  { name: 'IoT', slug: 'iot', category: 'Hardware & Deep Tech' },
  { name: 'Industrial IoT', slug: 'iiot', category: 'Hardware & Deep Tech' },
  { name: 'Smart Home', slug: 'smart-home', category: 'Hardware & Deep Tech' },
  { name: 'Smart Cities', slug: 'smart-cities', category: 'Hardware & Deep Tech' },
  { name: 'Sensors', slug: 'sensors', category: 'Hardware & Deep Tech' },
  { name: '3D Printing', slug: '3d-printing', category: 'Hardware & Deep Tech' },
  { name: 'Additive Manufacturing', slug: 'additive-mfg', category: 'Hardware & Deep Tech' },
  { name: 'Manufacturing Tech', slug: 'manufacturing-tech', category: 'Hardware & Deep Tech' },
  { name: 'Supply Chain', slug: 'supply-chain', category: 'Hardware & Deep Tech' },
  { name: 'DeepTech', slug: 'deeptech', category: 'Hardware & Deep Tech', popular: true },
  { name: 'Quantum Computing', slug: 'quantum-computing', category: 'Hardware & Deep Tech' },
  { name: 'Quantum Sensing', slug: 'quantum-sensing', category: 'Hardware & Deep Tech' },
  { name: 'Photonics', slug: 'photonics', category: 'Hardware & Deep Tech' },
  { name: 'Nanotechnology', slug: 'nanotech', category: 'Hardware & Deep Tech' },
  { name: 'Materials Science', slug: 'materials-science', category: 'Hardware & Deep Tech' },
  { name: 'Advanced Materials', slug: 'advanced-materials', category: 'Hardware & Deep Tech' },
  { name: 'Nuclear Fusion', slug: 'nuclear-fusion', category: 'Hardware & Deep Tech' },
  { name: 'Neuromorphic Computing', slug: 'neuromorphic', category: 'Hardware & Deep Tech' },
  { name: 'Optical Computing', slug: 'optical-computing', category: 'Hardware & Deep Tech' },
  { name: 'Bioelectronics', slug: 'bioelectronics', category: 'Hardware & Deep Tech' },
  { name: 'Wearable Tech', slug: 'wearable-tech', category: 'Hardware & Deep Tech' },
  { name: 'Consumer Hardware', slug: 'consumer-hardware', category: 'Hardware & Deep Tech' },
  { name: 'Prosumer Hardware', slug: 'prosumer-hardware', category: 'Hardware & Deep Tech' },

  // ─── AEROSPACE / DEFENSE (20+) ───
  { name: 'Aerospace', slug: 'aerospace', category: 'Aerospace & Defense', popular: true },
  { name: 'Space Tech', slug: 'space-tech', category: 'Aerospace & Defense', popular: true },
  { name: 'Satellites', slug: 'satellites', category: 'Aerospace & Defense' },
  { name: 'Small Satellites', slug: 'smallsats', category: 'Aerospace & Defense' },
  { name: 'Constellation Networks', slug: 'satellite-constellations', category: 'Aerospace & Defense' },
  { name: 'Launch Vehicles', slug: 'launch-vehicles', category: 'Aerospace & Defense' },
  { name: 'Reusable Rockets', slug: 'reusable-rockets', category: 'Aerospace & Defense' },
  { name: 'Space Manufacturing', slug: 'space-mfg', category: 'Aerospace & Defense' },
  { name: 'Space Debris', slug: 'space-debris', category: 'Aerospace & Defense' },
  { name: 'Space Mining', slug: 'space-mining', category: 'Aerospace & Defense' },
  { name: 'Earth Observation', slug: 'earth-observation', category: 'Aerospace & Defense' },
  { name: 'Satellite Imagery', slug: 'satellite-imagery', category: 'Aerospace & Defense' },
  { name: 'Defense Tech', slug: 'defense-tech', category: 'Aerospace & Defense' },
  { name: 'National Security', slug: 'national-security', category: 'Aerospace & Defense' },
  { name: 'Autonomous Systems', slug: 'autonomous-systems', category: 'Aerospace & Defense' },
  { name: 'Military AI', slug: 'military-ai', category: 'Aerospace & Defense' },
  { name: 'Aviation', slug: 'aviation', category: 'Aerospace & Defense' },
  { name: 'eVTOL', slug: 'evtol', category: 'Aerospace & Defense' },
  { name: 'Advanced Air Mobility', slug: 'aam', category: 'Aerospace & Defense' },
  { name: 'Hypersonics', slug: 'hypersonics', category: 'Aerospace & Defense' },

  // ─── MOBILITY / TRANSPORT (20+) ───
  { name: 'Mobility', slug: 'mobility', category: 'Mobility & Transport' },
  { name: 'Automotive', slug: 'automotive', category: 'Mobility & Transport' },
  { name: 'Autonomous Vehicles', slug: 'autonomous-vehicles', category: 'Mobility & Transport' },
  { name: 'Self-Driving Software', slug: 'self-driving-sw', category: 'Mobility & Transport' },
  { name: 'Ride Sharing', slug: 'ride-sharing', category: 'Mobility & Transport' },
  { name: 'Micromobility', slug: 'micromobility', category: 'Mobility & Transport' },
  { name: 'Fleet Management', slug: 'fleet-mgmt', category: 'Mobility & Transport' },
  { name: 'Logistics', slug: 'logistics', category: 'Mobility & Transport' },
  { name: 'Freight', slug: 'freight', category: 'Mobility & Transport' },
  { name: 'Trucking Tech', slug: 'trucking-tech', category: 'Mobility & Transport' },
  { name: 'Shipping & Maritime', slug: 'maritime', category: 'Mobility & Transport' },
  { name: 'Port Automation', slug: 'port-automation', category: 'Mobility & Transport' },
  { name: 'Rail Tech', slug: 'rail-tech', category: 'Mobility & Transport' },
  { name: 'Public Transit', slug: 'public-transit', category: 'Mobility & Transport' },
  { name: 'Parking Tech', slug: 'parking-tech', category: 'Mobility & Transport' },
  { name: 'Traffic Management', slug: 'traffic-mgmt', category: 'Mobility & Transport' },
  { name: 'Connected Vehicles', slug: 'connected-vehicles', category: 'Mobility & Transport' },
  { name: 'Vehicle-to-Everything', slug: 'v2x', category: 'Mobility & Transport' },
  { name: 'Route Optimization', slug: 'route-optimization', category: 'Mobility & Transport' },
  { name: 'Delivery Robots', slug: 'delivery-robots', category: 'Mobility & Transport' },

  // ─── REAL ESTATE / CONSTRUCTION (15+) ───
  { name: 'PropTech', slug: 'proptech', category: 'Real Estate & Construction' },
  { name: 'Real Estate', slug: 'real-estate', category: 'Real Estate & Construction' },
  { name: 'iBuying', slug: 'ibuying', category: 'Real Estate & Construction' },
  { name: 'Real Estate Investing', slug: 're-investing', category: 'Real Estate & Construction' },
  { name: 'Property Management', slug: 'property-mgmt', category: 'Real Estate & Construction' },
  { name: 'Short-term Rentals', slug: 'str', category: 'Real Estate & Construction' },
  { name: 'Coworking', slug: 'coworking', category: 'Real Estate & Construction' },
  { name: 'Coliving', slug: 'coliving', category: 'Real Estate & Construction' },
  { name: 'Construction Tech', slug: 'contech', category: 'Real Estate & Construction' },
  { name: 'Building Materials', slug: 'building-materials', category: 'Real Estate & Construction' },
  { name: 'Modular Construction', slug: 'modular-construction', category: 'Real Estate & Construction' },
  { name: 'Facility Management', slug: 'facility-mgmt', category: 'Real Estate & Construction' },
  { name: 'Real Estate Data', slug: 're-data', category: 'Real Estate & Construction' },
  { name: 'Mortgage Tech', slug: 'mortgage-tech', category: 'Real Estate & Construction' },
  { name: 'Home Insurance', slug: 'home-insurance', category: 'Real Estate & Construction' },

  // ─── TRAVEL / HOSPITALITY (10+) ───
  { name: 'Travel & Hospitality', slug: 'travel', category: 'Travel & Hospitality' },
  { name: 'Booking Platforms', slug: 'booking-platforms', category: 'Travel & Hospitality' },
  { name: 'Hotel Tech', slug: 'hotel-tech', category: 'Travel & Hospitality' },
  { name: 'Vacation Rentals', slug: 'vacation-rentals', category: 'Travel & Hospitality' },
  { name: 'Airline Tech', slug: 'airline-tech', category: 'Travel & Hospitality' },
  { name: 'Corporate Travel', slug: 'corp-travel', category: 'Travel & Hospitality' },
  { name: 'Adventure Travel', slug: 'adventure-travel', category: 'Travel & Hospitality' },
  { name: 'Local Experiences', slug: 'local-experiences', category: 'Travel & Hospitality' },
  { name: 'Travel Planning AI', slug: 'travel-ai', category: 'Travel & Hospitality' },
  { name: 'Sustainable Travel', slug: 'sustainable-travel', category: 'Travel & Hospitality' },

  // ─── GOV / IMPACT / NONPROFIT (15+) ───
  { name: 'GovTech', slug: 'govtech', category: 'Gov & Impact' },
  { name: 'Civic Tech', slug: 'civic-tech', category: 'Gov & Impact' },
  { name: 'Public Sector', slug: 'public-sector', category: 'Gov & Impact' },
  { name: 'Nonprofit Tech', slug: 'nonprofit-tech', category: 'Gov & Impact' },
  { name: 'Social Impact', slug: 'social-impact', category: 'Gov & Impact' },
  { name: 'Impact Investing', slug: 'impact-investing', category: 'Gov & Impact' },
  { name: 'Financial Inclusion', slug: 'financial-inclusion', category: 'Gov & Impact' },
  { name: 'Refugee Tech', slug: 'refugee-tech', category: 'Gov & Impact' },
  { name: 'Human Rights', slug: 'human-rights', category: 'Gov & Impact' },
  { name: 'Access to Education', slug: 'edu-access', category: 'Gov & Impact' },
  { name: 'Emergency Response', slug: 'emergency-response', category: 'Gov & Impact' },
  { name: 'Disaster Recovery', slug: 'disaster-recovery', category: 'Gov & Impact' },
  { name: 'Election Tech', slug: 'election-tech', category: 'Gov & Impact' },
  { name: 'Government Services', slug: 'gov-services', category: 'Gov & Impact' },
  { name: 'Public Safety', slug: 'public-safety', category: 'Gov & Impact' },

  // ─── SPORTS / FITNESS (10+) ───
  { name: 'Sports Tech', slug: 'sports-tech', category: 'Sports & Fitness' },
  { name: 'Fantasy Sports', slug: 'fantasy-sports', category: 'Sports & Fitness' },
  { name: 'Sports Betting', slug: 'sports-betting', category: 'Sports & Fitness' },
  { name: 'Fitness Apps', slug: 'fitness-apps', category: 'Sports & Fitness' },
  { name: 'Home Fitness', slug: 'home-fitness', category: 'Sports & Fitness' },
  { name: 'Connected Fitness', slug: 'connected-fitness-sports', category: 'Sports & Fitness' },
  { name: 'Athlete Performance', slug: 'athlete-performance', category: 'Sports & Fitness' },
  { name: 'Outdoor Sports', slug: 'outdoor-sports', category: 'Sports & Fitness' },
  { name: 'Sports Analytics', slug: 'sports-analytics', category: 'Sports & Fitness' },
  { name: 'Youth Sports', slug: 'youth-sports', category: 'Sports & Fitness' },

  // ─── WEB3 (SEPARATE FROM FINTECH — 20+) ───
  { name: 'DAOs', slug: 'daos', category: 'Web3' },
  { name: 'Smart Contract Platforms', slug: 'smart-contract-platforms', category: 'Web3' },
  { name: 'Web3 Social', slug: 'web3-social', category: 'Web3' },
  { name: 'Decentralized Identity', slug: 'decentralized-identity', category: 'Web3' },
  { name: 'On-Chain Analytics', slug: 'onchain-analytics', category: 'Web3' },
  { name: 'Blockchain Infrastructure', slug: 'blockchain-infra', category: 'Web3' },
  { name: 'Layer 2', slug: 'layer2', category: 'Web3' },
  { name: 'Rollup Infrastructure', slug: 'rollup-infra', category: 'Web3' },
  { name: 'Zero Knowledge', slug: 'zk', category: 'Web3' },
  { name: 'Cross-chain', slug: 'cross-chain', category: 'Web3' },
  { name: 'Web3 Gaming Infrastructure', slug: 'web3-gaming-infra', category: 'Web3' },
  { name: 'NFT Marketplaces', slug: 'nft-marketplaces', category: 'Web3' },
  { name: 'Web3 Wallets', slug: 'web3-wallets', category: 'Web3' },
  { name: 'MEV Infrastructure', slug: 'mev-infra', category: 'Web3' },
  { name: 'DeFi Infrastructure', slug: 'defi-infra', category: 'Web3' },
  { name: 'Prediction Markets', slug: 'prediction-markets', category: 'Web3' },
  { name: 'Crypto Custody', slug: 'crypto-custody', category: 'Web3' },
  { name: 'Restaking', slug: 'restaking', category: 'Web3' },
  { name: 'RWA Tokenization', slug: 'rwa', category: 'Web3' },
  { name: 'Bitcoin L2', slug: 'bitcoin-l2', category: 'Web3' },
]

// ─── HELPERS ───

export function getCategories(): string[] {
  const set = new Set<string>()
  VENTURE_DOMAINS.forEach(d => set.add(d.category))
  return Array.from(set).sort()
}

export function searchDomains(query: string, limit = 15): DomainDef[] {
  if (!query || query.length < 1) return []
  const q = query.toLowerCase().trim()

  const startsWith: DomainDef[] = []
  const contains: DomainDef[] = []
  const aliasMatch: DomainDef[] = []

  for (const d of VENTURE_DOMAINS) {
    const nameLower = d.name.toLowerCase()
    if (nameLower.startsWith(q)) {
      startsWith.push(d)
    } else if (nameLower.includes(q)) {
      contains.push(d)
    } else if (d.aliases?.some(a => a.toLowerCase().includes(q))) {
      aliasMatch.push(d)
    }
  }

  return [...startsWith, ...contains, ...aliasMatch].slice(0, limit)
}

export function getPopularDomains(limit = 20): DomainDef[] {
  return VENTURE_DOMAINS.filter(d => d.popular).slice(0, limit)
}